//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSFilterPart.VisualWebPart1 {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class VisualWebPart1 {
        
        protected global::System.Web.UI.WebControls.TextBox Filter;
        
        protected global::System.Web.UI.WebControls.Button FilterButton;
        
        protected global::System.Web.UI.WebControls.HiddenField HiddenFilterValue;
        
        public static implicit operator global::System.Web.UI.TemplateControl(VisualWebPart1 target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlFilter() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.Filter = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Filter";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlFilterButton() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.FilterButton = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "FilterButton";
            @__ctrl.Text = "Filter";
            @__ctrl.Click -= new System.EventHandler(this.FilterButton_Click);
            @__ctrl.Click += new System.EventHandler(this.FilterButton_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHiddenFilterValue() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.HiddenFilterValue = @__ctrl;
            @__ctrl.ID = "HiddenFilterValue";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::JSFilterPart.VisualWebPart1.VisualWebPart1 @__ctrl) {
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControlFilter();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Button @__ctrl2;
            @__ctrl2 = this.@__BuildControlFilterButton();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.HiddenField @__ctrl3;
            @__ctrl3 = this.@__BuildControlHiddenFilterValue();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"
<!DOCTYPE
html>

<html>

<head>
  
<title></title>
    <script src=""../_layouts/15/JSFilterPart/JS/jquery-1.9.1.js""></script>
    <script src=""../_layouts/15/JSFilterPart/JS/jquery-ui-1.10.3.custom.js""></script>
    <link href=""../_layouts/15/JSFilterPart/CSS/ui-lightness/jquery-ui-1.10.3.custom.css"" rel=""stylesheet"" />
    <script type=""text/javascript"" >
     
        $(function () {
            if (typeof FilterValues == 'undefined') {

                FilterValues = [];

            }
           /* var FilterValues = [
     ""ActionScript"",
     ""AppleScript"",
     ""Asp"",
     ""BASIC"",
     ""C"",
     ""C++"",
     ""Clojure"",
     ""COBOL"",
     ""ColdFusion"",
     ""Erlang"",
     ""Fortran"",
     ""Groovy"",
     ""Haskell"",
     ""Java"",
     ""JavaScript"",
     ""Lisp"",
     ""Perl"",
     ""PHP"",
     ""Python"",
     ""Ruby"",
     ""Scala"",
     ""Scheme""
            ];*/

            $(""#");
        @__w.Write( Filter.ClientID );

            @__w.Write("\").autocomplete({\r\n                source: FilterValues,\r\n                focus: " +
                    "function (event, ui) {\r\n                    $(\"#");
                @__w.Write( Filter.ClientID );

            @__w.Write("\").val(ui.item.value);\r\n                    return false;\r\n                },\r\n  " +
                    "              select: function (event, ui) {\r\n                    $(\"#");
                @__w.Write( HiddenFilterValue.ClientID );

            @__w.Write("\").val(ui.item.ID);\r\n                    return false;\r\n                }\r\n      " +
                    "      });\r\n           \r\n        });\r\n    </script>\r\n    </head>\r\n    <body>\r\n   " +
                    "     ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("&nbsp;");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n\r\n        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n\r\n    </body>\r\n    </html>\r\n");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
