/*
Deployment script for Meerkat

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Meerkat"
:setvar DefaultFilePrefix "Meerkat"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[IndicatorShortName].[HierarchyLevel]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyLevel', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'IndicatorShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[IndicatorShortName].[HierarchyName]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyName', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'IndicatorShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[ProgrammeShortName].[HierarchyLevel]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyLevel', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'ProgrammeShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[ProgrammeShortName].[HierarchyName]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyName', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'ProgrammeShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[ProjectShortName].[HierarchyLevel]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyLevel', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'ProjectShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[ProjectShortName].[HierarchyName]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyName', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'ProjectShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[ReportLevel].[HiearchyLevel]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HiearchyLevel', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'ReportLevel';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[ReportLevel].[HierarchyName]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyName', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'ReportLevel';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[SectorShortName].[HierarchyLevel]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyLevel', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'SectorShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[SectorShortName].[HierarchyName]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyName', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'SectorShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[SubsectorShortName].[HierarchyLevel]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyLevel', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'SubsectorShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[SubsectorShortName].[HierarchyName]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyName', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector', @level2type = N'COLUMN', @level2name = N'SubsectorShortName';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[HierarchyLevel]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyLevel', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector';


GO
PRINT N'Dropping [OLAP_GEN].[IndicatorByProjectSector].[HierarchyName]...';


GO
EXECUTE sp_dropextendedproperty @name = N'HierarchyName', @level0type = N'SCHEMA', @level0name = N'OLAP_GEN', @level1type = N'VIEW', @level1name = N'IndicatorByProjectSector';


GO
PRINT N'Dropping DF_Project_ProjectType_ID...';


GO
ALTER TABLE [app].[Project] DROP CONSTRAINT [DF_Project_ProjectType_ID];


GO
PRINT N'Dropping FK_Project_ProjectType...';


GO
ALTER TABLE [app].[Project] DROP CONSTRAINT [FK_Project_ProjectType];


GO
PRINT N'Altering [app].[Project]...';


GO
ALTER TABLE [app].[Project] ALTER COLUMN [ProjectType_ID] INT NULL;


GO
PRINT N'Altering [settings].[GlobalSettings]...';


GO
ALTER TABLE [settings].[GlobalSettings] DROP COLUMN [LocalName];


GO
PRINT N'Creating [settings].[TablesToExport]...';


GO
CREATE TABLE [settings].[TablesToExport] (
    [TablesToExport_ID] INT           IDENTITY (1, 1) NOT NULL,
    [Table_Schema]      VARCHAR (255) NOT NULL,
    [Table_Name]        VARCHAR (255) NOT NULL,
    [Export]            BIT           NOT NULL,
    [Active]            INT           NOT NULL,
    [sys_CreatedBy]     VARCHAR (255) NOT NULL,
    [sys_CreatedOn]     DATETIME      NOT NULL,
    [sys_ModifiedBy]    VARCHAR (255) NOT NULL,
    [sys_ModifiedOn]    DATETIME      NOT NULL,
    CONSTRAINT [PK__TablesTo__0C91590DA0E643C6] PRIMARY KEY CLUSTERED ([TablesToExport_ID] ASC)
);


GO
PRINT N'Creating DF_Project_ProjectType_ID...';


GO
ALTER TABLE [app].[Project]
    ADD CONSTRAINT [DF_Project_ProjectType_ID] DEFAULT ((2)) FOR [ProjectType_ID];


GO
PRINT N'Creating DF__TablesToE__Activ__64C2D10D...';


GO
ALTER TABLE [settings].[TablesToExport]
    ADD CONSTRAINT [DF__TablesToE__Activ__64C2D10D] DEFAULT ((1)) FOR [Active];


GO
PRINT N'Creating DF__TablesToE__Expor__63CEACD4...';


GO
ALTER TABLE [settings].[TablesToExport]
    ADD CONSTRAINT [DF__TablesToE__Expor__63CEACD4] DEFAULT ((0)) FOR [Export];


GO
PRINT N'Creating DF_TablesToExport_sys_CreatedBy...';


GO
ALTER TABLE [settings].[TablesToExport]
    ADD CONSTRAINT [DF_TablesToExport_sys_CreatedBy] DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating DF_TablesToExport_sys_CreatedOn...';


GO
ALTER TABLE [settings].[TablesToExport]
    ADD CONSTRAINT [DF_TablesToExport_sys_CreatedOn] DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating DF_TablesToExport_sys_ModifiedBy...';


GO
ALTER TABLE [settings].[TablesToExport]
    ADD CONSTRAINT [DF_TablesToExport_sys_ModifiedBy] DEFAULT (user_name()) FOR [sys_ModifiedBy];


GO
PRINT N'Creating DF_TablesToExport_sys_ModifiedOn...';


GO
ALTER TABLE [settings].[TablesToExport]
    ADD CONSTRAINT [DF_TablesToExport_sys_ModifiedOn] DEFAULT (getdate()) FOR [sys_ModifiedOn];


GO
PRINT N'Creating FK_Project_ProjectType...';


GO
ALTER TABLE [app].[Project] WITH NOCHECK
    ADD CONSTRAINT [FK_Project_ProjectType] FOREIGN KEY ([ProjectType_ID]) REFERENCES [app].[ProjectType] ([ProjectType_ID]);


GO
PRINT N'Creating FK_TablesToExport_ActiveType...';


GO
ALTER TABLE [settings].[TablesToExport] WITH NOCHECK
    ADD CONSTRAINT [FK_TablesToExport_ActiveType] FOREIGN KEY ([Active]) REFERENCES [Core].[ActiveType] ([ID]);


GO
PRINT N'Refreshing [mm].[ALL_OutcomeMenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[ALL_OutcomeMenuGroup]';


GO
PRINT N'Refreshing [mm].[ALL_OutcomeMenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[ALL_OutcomeMenuLink]';


GO
PRINT N'Refreshing [mm].[ALL_ProgrammeMenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[ALL_ProgrammeMenuGroup]';


GO
PRINT N'Refreshing [OLAP_GEN].[Activity]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[Activity]';


GO
PRINT N'Refreshing [OLAP_GEN].[AgeBand]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[AgeBand]';


GO
PRINT N'Refreshing [OLAP_GEN].[FrameworkDetail_Indicator]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[FrameworkDetail_Indicator]';


GO
PRINT N'Refreshing [OLAP_GEN].[Indicator]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[Indicator]';


GO
PRINT N'Refreshing [OLAP_GEN].[IndicatorByProgram]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[IndicatorByProgram]';


GO
PRINT N'Refreshing [OLAP_GEN].[IndicatorByProjectSector]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[IndicatorByProjectSector]';


GO
PRINT N'Refreshing [OLAP_GEN].[Milestone]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[Milestone]';


GO
PRINT N'Refreshing [OLAP_GEN].[PeopleReachedValues]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[PeopleReachedValues]';


GO
PRINT N'Refreshing [OLAP_GEN].[Project]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[Project]';


GO
PRINT N'Refreshing [OLAP_GEN].[StatusValues]...';


GO
EXECUTE sp_refreshsqlmodule N'[OLAP_GEN].[StatusValues]';


GO
PRINT N'Refreshing [rpt].[FormResponsesByProject]...';


GO
EXECUTE sp_refreshsqlmodule N'[rpt].[FormResponsesByProject]';


GO
PRINT N'Refreshing [rpt].[ProjectStatusScorecard]...';


GO
EXECUTE sp_refreshsqlmodule N'[rpt].[ProjectStatusScorecard]';


GO
PRINT N'Refreshing [rpt].[vwFormResponsesCount]...';


GO
EXECUTE sp_refreshsqlmodule N'[rpt].[vwFormResponsesCount]';


GO
PRINT N'Refreshing [rpt].[vwPeopleReached]...';


GO
EXECUTE sp_refreshsqlmodule N'[rpt].[vwPeopleReached]';


GO
PRINT N'Refreshing [mm].[Outcome1MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome1MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome2MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome2MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome3MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome3MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome4MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome4MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome5MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome5MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome6MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome6MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome7MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome7MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome8MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome8MenuGroup]';


GO
PRINT N'Refreshing [mm].[Outcome1MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome1MenuLink]';


GO
PRINT N'Refreshing [mm].[Outcome2MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome2MenuLink]';


GO
PRINT N'Refreshing [mm].[Outcome3MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome3MenuLink]';


GO
PRINT N'Refreshing [mm].[Outcome4MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome4MenuLink]';


GO
PRINT N'Refreshing [mm].[Outcome5MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome5MenuLink]';


GO
PRINT N'Refreshing [mm].[Outcome6MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome6MenuLink]';


GO
PRINT N'Refreshing [mm].[Outcome7MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome7MenuLink]';


GO
PRINT N'Refreshing [mm].[Outcome8MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Outcome8MenuLink]';


GO
PRINT N'Refreshing [mm].[ALL_ProgrammeMenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[ALL_ProgrammeMenuLink]';


GO
PRINT N'Refreshing [mm].[Programme1MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme1MenuGroup]';


GO
PRINT N'Refreshing [mm].[Programme2MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme2MenuGroup]';


GO
PRINT N'Refreshing [mm].[Programme3MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme3MenuGroup]';


GO
PRINT N'Refreshing [mm].[Programme4MenuGroup]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme4MenuGroup]';


GO
PRINT N'Refreshing [mm].[Programme1MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme1MenuLink]';


GO
PRINT N'Refreshing [mm].[Programme2MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme2MenuLink]';


GO
PRINT N'Refreshing [mm].[Programme3MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme3MenuLink]';


GO
PRINT N'Refreshing [mm].[Programme4MenuLink]...';


GO
EXECUTE sp_refreshsqlmodule N'[mm].[Programme4MenuLink]';


GO
PRINT N'Creating [app].[Activity].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Activity';


GO
PRINT N'Creating [app].[Impact].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'2', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Impact';


GO
PRINT N'Creating [app].[Indicator].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'6', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Indicator';


GO
PRINT N'Creating [app].[IndicatorLocation].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'IndicatorLocation';


GO
PRINT N'Creating [app].[IndicatorSimpleType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'IndicatorSimpleType';


GO
PRINT N'Creating [app].[IndicatorType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'IndicatorType';


GO
PRINT N'Creating [app].[Milestone].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'6', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Milestone';


GO
PRINT N'Creating [app].[MilestoneLocation].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'MilestoneLocation';


GO
PRINT N'Creating [app].[MilestoneType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'MilestoneType';


GO
PRINT N'Creating [app].[Outcome].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'3', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Outcome';


GO
PRINT N'Creating [app].[OutcomeOrganization].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'4', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'OutcomeOrganization';


GO
PRINT N'Creating [app].[OutcomePersonRole].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'4', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'OutcomePersonRole';


GO
PRINT N'Creating [app].[Output].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'4', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Output';


GO
PRINT N'Creating [app].[OutputOutputLink].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'OutputOutputLink';


GO
PRINT N'Creating [app].[OutputPersonRole].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'OutputPersonRole';


GO
PRINT N'Creating [app].[Programme].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Programme';


GO
PRINT N'Creating [app].[Project].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'4', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Project';


GO
PRINT N'Creating [app].[ProjectType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'ProjectType';


GO
PRINT N'Creating [app].[Sector].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'2', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'Sector';


GO
PRINT N'Creating [app].[SubOutput].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'SubOutput';


GO
PRINT N'Creating [app].[SubOutputPersonRole].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'6', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'SubOutputPersonRole';


GO
PRINT N'Creating [app].[SubOutputSubOutputLink].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'6', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'SubOutputSubOutputLink';


GO
PRINT N'Creating [app].[SubSector].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'3', @level0type = N'SCHEMA', @level0name = N'app', @level1type = N'TABLE', @level1name = N'SubSector';


GO
PRINT N'Creating [Core].[ActiveType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'0', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'ActiveType';


GO
PRINT N'Creating [Core].[DataSource].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'DataSource';


GO
PRINT N'Creating [Core].[DataVersion].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'DataVersion';


GO
PRINT N'Creating [Core].[DimDate].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'DimDate';


GO
PRINT N'Creating [Core].[DimMunicipalityGEOM].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'0', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'DimMunicipalityGEOM';


GO
PRINT N'Creating [Core].[Location].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'2', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'Location';


GO
PRINT N'Creating [Core].[LocationType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'LocationType';


GO
PRINT N'Creating [Core].[Organization].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'2', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'Organization';


GO
PRINT N'Creating [Core].[OrganizationPersonRole].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'3', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'OrganizationPersonRole';


GO
PRINT N'Creating [Core].[OrganizationType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'OrganizationType';


GO
PRINT N'Creating [Core].[Person].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'Person';


GO
PRINT N'Creating [Core].[ReportingPeriod].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'ReportingPeriod';


GO
PRINT N'Creating [Core].[Role].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'Role';


GO
PRINT N'Creating [Core].[StatusType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'Core', @level1type = N'TABLE', @level1name = N'StatusType';


GO
PRINT N'Creating [dbo].[templateMenueGroup].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'0', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'templateMenueGroup';


GO
PRINT N'Creating [disagg].[Age].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Age';


GO
PRINT N'Creating [disagg].[AgeBand].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'AgeBand';


GO
PRINT N'Creating [disagg].[CommunityType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'CommunityType';


GO
PRINT N'Creating [disagg].[Donor].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Donor';


GO
PRINT N'Creating [disagg].[Facility].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'2', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Facility';


GO
PRINT N'Creating [disagg].[FacilityType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'FacilityType';


GO
PRINT N'Creating [disagg].[Framework].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'3', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Framework';


GO
PRINT N'Creating [disagg].[FrameworkDetail].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'4', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'FrameworkDetail';


GO
PRINT N'Creating [disagg].[FrameworkDetail_Indicator].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'FrameworkDetail_Indicator';


GO
PRINT N'Creating [disagg].[FrameworkDetail_Project].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'FrameworkDetail_Project';


GO
PRINT N'Creating [disagg].[Gender].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Gender';


GO
PRINT N'Creating [disagg].[Group].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Group';


GO
PRINT N'Creating [disagg].[Institution].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Institution';


GO
PRINT N'Creating [disagg].[Project_ResultArea].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'Project_ResultArea';


GO
PRINT N'Creating [disagg].[ResultArea].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'ResultArea';


GO
PRINT N'Creating [disagg].[StrategicElement].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'disagg', @level1type = N'TABLE', @level1name = N'StrategicElement';


GO
PRINT N'Creating [forms].[Category].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'Category';


GO
PRINT N'Creating [forms].[Event].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'Event';


GO
PRINT N'Creating [forms].[Event_Indicator_Rollup].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'Event_Indicator_Rollup';


GO
PRINT N'Creating [forms].[EventRegister].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'6', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'EventRegister';


GO
PRINT N'Creating [forms].[Form].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'6', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'Form';


GO
PRINT N'Creating [forms].[FormResponse].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'FormResponse';


GO
PRINT N'Creating [forms].[Question].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'8', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'Question';


GO
PRINT N'Creating [forms].[QuestionType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'QuestionType';


GO
PRINT N'Creating [forms].[Response].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'9', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'Response';


GO
PRINT N'Creating [forms].[RollupType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'forms', @level1type = N'TABLE', @level1name = N'RollupType';


GO
PRINT N'Creating [RBM].[IndicatorValues].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'RBM', @level1type = N'TABLE', @level1name = N'IndicatorValues';


GO
PRINT N'Creating [RBM].[MilestoneValues].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'RBM', @level1type = N'TABLE', @level1name = N'MilestoneValues';


GO
PRINT N'Creating [RBM].[PeopleReachedValues].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'8', @level0type = N'SCHEMA', @level0name = N'RBM', @level1type = N'TABLE', @level1name = N'PeopleReachedValues';


GO
PRINT N'Creating [RBM].[StatusValues].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'RBM', @level1type = N'TABLE', @level1name = N'StatusValues';


GO
PRINT N'Creating [rpt].[CustomReport].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'2', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'CustomReport';


GO
PRINT N'Creating [rpt].[CustomReport_Calendar].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'3', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'CustomReport_Calendar';


GO
PRINT N'Creating [rpt].[CustomReport_Indicator].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'CustomReport_Indicator';


GO
PRINT N'Creating [rpt].[CustomReport_Project].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'CustomReport_Project';


GO
PRINT N'Creating [rpt].[CustomReport_ResponsiblePerson].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'3', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'CustomReport_ResponsiblePerson';


GO
PRINT N'Creating [rpt].[CustomReportType].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'CustomReportType';


GO
PRINT N'Creating [rpt].[DonorReport].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'DonorReport';


GO
PRINT N'Creating [rpt].[DonorReport_Indicator].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'7', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'DonorReport_Indicator';


GO
PRINT N'Creating [rpt].[DonorReport_Project].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'5', @level0type = N'SCHEMA', @level0name = N'rpt', @level1type = N'TABLE', @level1name = N'DonorReport_Project';


GO
PRINT N'Creating [settings].[GlobalSettings].[RelationshipDepth]...';


GO
EXECUTE sp_addextendedproperty @name = N'RelationshipDepth', @value = N'1', @level0type = N'SCHEMA', @level0name = N'settings', @level1type = N'TABLE', @level1name = N'GlobalSettings';


GO
PRINT N'Refreshing [Core].[sp_MilestoneCaptureProgress]...';


GO
EXECUTE sp_refreshsqlmodule N'[Core].[sp_MilestoneCaptureProgress]';


GO
PRINT N'Refreshing [Core].[usp_MilestoneCaptureProgress]...';


GO
EXECUTE sp_refreshsqlmodule N'[Core].[usp_MilestoneCaptureProgress]';


GO
PRINT N'Refreshing [dbo].[uspActivityProgress]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[uspActivityProgress]';


GO
PRINT N'Refreshing [dbo].[uspIndicatorsList]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[uspIndicatorsList]';


GO
PRINT N'Refreshing [dbo].[uspProject_ActivityProgress]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[uspProject_ActivityProgress]';


GO

/*GeoSpatialData*/

IF ( EXISTS ( SELECT    [master].[dbo].[sysdatabases].[name]
              FROM      master.dbo.sysdatabases
              WHERE     ( '[' + [master].[dbo].[sysdatabases].[name] + ']' = 'SpatialProvince'
                          OR [master].[dbo].[sysdatabases].[name] = 'SpatialProvince'
                        ) ) ) 
    BEGIN
        INSERT  INTO Meerkat.Core.DimMunicipalityGEOM
                ( [Meerkat].[Core].[DimMunicipalityGEOM].[ID] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[LBL] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[FIP] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[MMT_ID] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[SHORT__FRM] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[LONG_FRM] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[ADM0] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[ADM1] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[ADM2] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[ADM3] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[ADM4] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[ADM5] ,
                  [Meerkat].[Core].[DimMunicipalityGEOM].[geom]
                )
                SELECT  [SpatialProvince].[dbo].[SimpleProvince].[Location_ID] AS [ID] ,
                        [SpatialProvince].[dbo].[SimpleProvince].[ISO] AS [LBL] ,
                        '' AS [FIP] ,
                        '' [MMT_ID] ,
                        '' [SHORT__FRM] ,
                        '' [LONG_FRM] ,
                        [SpatialProvince].[dbo].[SimpleProvince].[ADM0] ,
                        [SpatialProvince].[dbo].[SimpleProvince].[ADM1] ,
                        '' [ADM2] ,
                        '' [ADM3] ,
                        '' [ADM4] ,
                        '' [ADM5] ,
                        [SpatialProvince].[dbo].[SimpleProvince].[Geog] AS [geom]
                FROM    [SpatialProvince].dbo.[SimpleProvince] 
    END

/*ALTER TABLE app.SubOutput ADD CONSTRAINT
    DF_SubOutput_Active DEFAULT 1 FOR Active
GO*/


/* Insert Data */

/*Insert Core data*/
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT  [Core].[ActiveType]
        ( [Core].[ActiveType].[ID] ,
          [Core].[ActiveType].[Code] ,
          [Core].[ActiveType].[Name]
        )
        SELECT  -1 ,
                N'Deleted' ,
                N'Deleted'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.ActiveType
                             WHERE  [Core].[ActiveType].[ID] = -1 )
GO

INSERT  [Core].[ActiveType]
        ( [Core].[ActiveType].[ID] ,
          [Core].[ActiveType].[Code] ,
          [Core].[ActiveType].[Name]
        )
        SELECT  0 ,
                N'InActive' ,
                N'InActive'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.ActiveType
                             WHERE  [Core].[ActiveType].[ID] = 0 )
GO
INSERT  [Core].[ActiveType]
        ( [Core].[ActiveType].[ID] ,
          [Core].[ActiveType].[Code] ,
          [Core].[ActiveType].[Name]
        )
        SELECT  1 ,
                N'Active' ,
                N'Active'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.ActiveType
                             WHERE  [Core].[ActiveType].[ID] = 1 )
GO

/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET IDENTITY_INSERT Core.StatusType ON 

INSERT  INTO [Core].StatusType
        ( [Core].[StatusType].[ID] ,
          [Core].[StatusType].[Code] ,
          [Core].[StatusType].[Name] ,
          [Core].[StatusType].[Value],
          [Core].[StatusType].[Active],
		  [Core].[StatusType].[BusinessKey]
        )
        SELECT  0 ,
                '+' ,
                'On Target' ,
                1,
                1,
				'+'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.StatusType
                             WHERE  [Core].[StatusType].[Code] = '+' )
        UNION ALL
        SELECT  1 ,
                '=' ,
                'Acceptable' ,
                0,
                1,
				'='
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.StatusType
                             WHERE  [Core].[StatusType].[Code] = '=' )
        UNION ALL
        SELECT  2 ,
                '-' ,
                'Sub par' ,
                -1,
                1,
				'-'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.StatusType
                             WHERE  [Core].[StatusType].[Code] = '-' )

GO


SET IDENTITY_INSERT Core.StatusType OFF
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET IDENTITY_INSERT Core.DataVersion ON 
INSERT  INTO Core.DataVersion
        ( [Core].[DataVersion].[Active] ,
          [Core].[DataVersion].[Code] ,
          [Core].[DataVersion].[DataVersion_ID] ,
          [Core].[DataVersion].[Name] ,
          [Core].[DataVersion].[Order] ,
          [Core].[DataVersion].[Description],
		  [Core].[DataVersion].[BusinessKey]
        )
        SELECT  1 ,
                '0' ,
                0 ,
                'External' ,
                0 ,
                '',
				'0'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.DataVersion
                             WHERE  [Core].[DataVersion].[DataVersion_ID] = 0 )

INSERT  INTO Core.DataVersion
        ( [Core].[DataVersion].[Active] ,
          [Core].[DataVersion].[Code] ,
          [Core].[DataVersion].[DataVersion_ID] ,
          [Core].[DataVersion].[Name] ,
          [Core].[DataVersion].[Order] ,
          [Core].[DataVersion].[Description],
		  [Core].[DataVersion].[BusinessKey]
        )
        SELECT  1 ,
                '1' ,
                1 ,
                'Publish' ,
                1 ,
                '',
				'1'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.DataVersion
                             WHERE  [Core].[DataVersion].[DataVersion_ID] = 1 )

INSERT  INTO Core.DataVersion
        ( [Core].[DataVersion].[Active] ,
          [Core].[DataVersion].[Code] ,
          [Core].[DataVersion].[DataVersion_ID] ,
          [Core].[DataVersion].[Name] ,
          [Core].[DataVersion].[Order] ,
          [Core].[DataVersion].[Description],
		  [Core].[DataVersion].[BusinessKey]
        )
        SELECT  1 ,
                '2' ,
                2 ,
                'Final Draft' ,
                2 ,
                '',
				'2'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.DataVersion
                             WHERE  [Core].[DataVersion].[DataVersion_ID] = 3 )

INSERT  INTO Core.DataVersion
        ( [Core].[DataVersion].[Active] ,
          [Core].[DataVersion].[Code] ,
          [Core].[DataVersion].[DataVersion_ID] ,
          [Core].[DataVersion].[Name] ,
          [Core].[DataVersion].[Order] ,
          [Core].[DataVersion].[Description],
		  [Core].[DataVersion].[BusinessKey]
        )
        SELECT  1 ,
                '3' ,
                3 ,
                'First Draft' ,
                3 ,
                '',
				'3'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.DataVersion
                             WHERE  [Core].[DataVersion].[DataVersion_ID] = 4 )


SET IDENTITY_INSERT  Core.DataVersion OFF
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET NOCOUNT ON;
IF ( SELECT COUNT(1)
     FROM   Core.DimDate
   ) = 0 
    BEGIN
--Alter start

        DECLARE @StartDate DATETIME ,
            @EndDate DATETIME ,
            @Date DATETIME;

        SET @StartDate = '1990/01/01';
        SET @EndDate = '2025/12/31';
        SET @Date = @StartDate;

        WHILE @Date <= @EndDate 
            BEGIN

                DECLARE @IsLeapYear BIT
                IF ( ( YEAR(@Date) % 4 = 0 )
                     AND ( YEAR(@Date) % 100 != 0
                           OR YEAR(@Date) % 400 = 0
                         )
                   ) 
                    BEGIN

                        SELECT  @IsLeapYear = 1;

                    END
                ELSE 
                    BEGIN

                        SELECT  @IsLeapYear = 0;

                    END

                DECLARE @IsWeekend BIT
                IF ( DATEPART(dw, @Date) = 1
                     OR DATEPART(dw, @Date) = 7
                   ) 
                    BEGIN

                        SELECT  @IsWeekend = 1;

                    END
                ELSE 
                    BEGIN

                        SELECT  @IsWeekend = 0;

                    END

                INSERT  INTO Core.DimDate
                        ( [Core].[DimDate].[DateID] ,
                          [Core].[DimDate].[Date] ,
                          [Core].[DimDate].[Day] ,
                          [Core].[DimDate].[DaySuffix] ,
                          [Core].[DimDate].[USDayOfWeek] ,
                          [Core].[DimDate].[DayOfWeek] ,
                          [Core].[DimDate].[DOWInMonth] ,
                          [Core].[DimDate].[DayOfYear] ,
                          [Core].[DimDate].[WeekOfYear] ,
                          [Core].[DimDate].[WeekOfMonth] ,
                          [Core].[DimDate].[MonthNumber] ,
                          [Core].[DimDate].[MonthName] ,
                          [Core].[DimDate].[Quarter] ,
                          [Core].[DimDate].[QuarterName] ,
                          [Core].[DimDate].[YearName] ,
                          [Core].[DimDate].[YearNumber] ,
                          [Core].[DimDate].[StandardDate] ,
                          [Core].[DimDate].[IsPublicHoliday] ,
                          [Core].[DimDate].[HolidayText]
                        )
                VALUES  ( REPLACE(CONVERT(NVARCHAR(50), CONVERT(DATE, @Date)),
                                  '-', '') ,
                          @Date ,
                          DATEPART(DAY, @Date) ,
                          SUBSTRING(CONVERT(CHAR(3), DATENAME(DW, @Date)), 1,
                                    3) ,
                          DATEPART(WEEKDAY, @Date) ,
                          CASE WHEN DATEPART(WEEKDAY, @Date) - 1 = 0 THEN 1
                               WHEN DATEPART(WEEKDAY, @Date) - 1 = 6 THEN 7
                               ELSE DATEPART(WEEKDAY, @Date) - 1
                          END ,
                          DATEPART(DAY,
                                   ( DATEADD(S, -1,
                                             DATEADD(MM,
                                                     DATEDIFF(M, 0, @Date) + 1,
                                                     0)) )) ,
                          DATEPART(DAYOFYEAR, @Date) ,
                          DATEPART(WEEK, @Date) ,
                          ( DATEPART(DAY, @Date) / 7 ) + 1 ,
                          DATEPART(MONTH, @Date) ,
                          DATENAME(MONTH, @Date) ,
                          DATEPART(QUARTER, @Date) ,
                          'Quarter ' + CONVERT(NVARCHAR(255), DATEPART(QUARTER,
                                                              @Date)) ,
                          CONVERT(CHAR(4), DATEPART(YEAR, @Date)) ,
                          DATEPART(YEAR, @Date) ,
                          NULL ,
                          NULL ,
                          NULL 
                        );

                SET @Date += 1;

            END

        PRINT 'Updated Table [Shared.DimDate]';

    END
GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT  INTO Core.ReportingPeriod
        ( [Core].[ReportingPeriod].[ReportingPeriod] ,
          [Core].[ReportingPeriod].[StartDateID] ,
          [Core].[ReportingPeriod].[EndDateID] ,
          [Core].[ReportingPeriod].[FirstCycleDate] ,
          [Core].[ReportingPeriod].[LastCycleDate] ,
          [Core].[ReportingPeriod].[YearName] ,
          [Core].[ReportingPeriod].[YearNumber],
          [Core].[ReportingPeriod].[Summary],
		  [Core].[ReportingPeriod].[BusinessKey]
        )
        SELECT  rc.[ReportingPeriod] ,
                rc.[StartDateID] ,
                rc.[EndDateID] ,
                rc.[FirstCycleDate] ,
                rc.[LastCycleDate] ,
                rc.[YearName] ,
                rc.[YearNumber],
                CONCAT(rc.[YearNumber],' - ',rc.[ReportingPeriod]),
				rc.[ReportingPeriod]
        FROM    [Core].[ReportCycle] AS rc
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   Core.ReportingPeriod
                             WHERE  [Core].[ReportingPeriod].[StartDateID] = rc.StartDateID
                                    AND [Core].[ReportingPeriod].[EndDateID] = rc.EndDateID )



GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET IDENTITY_INSERT [app].[MilestoneType] ON 

GO
INSERT  [app].[MilestoneType]
        ( [app].[MilestoneType].[MilestoneTypeID] ,
          [app].[MilestoneType].[Code] ,
          [app].[MilestoneType].[Name] ,
          [app].[MilestoneType].[Active],
		  [app].[MilestoneType].[BusinessKey]
        )
        SELECT  4 ,
                N'Project' ,
                N'Project' ,
                1,
				N'Project'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.MilestoneType
                             WHERE  [app].[MilestoneType].[MilestoneTypeID] = 4 )
GO
INSERT  [app].[MilestoneType]
        ( [app].[MilestoneType].[MilestoneTypeID] ,
          [app].[MilestoneType].[Code] ,
          [app].[MilestoneType].[Name] ,
          [app].[MilestoneType].[Active],
		  [app].[MilestoneType].[BusinessKey]
        )
        SELECT  5 ,
                N'Activity' ,
                N'Activity' ,
                1,
				N'Activity'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.MilestoneType
                             WHERE  [app].[MilestoneType].[MilestoneTypeID] = 5 )
GO
SET IDENTITY_INSERT [app].[MilestoneType] OFF
GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET IDENTITY_INSERT [app].[IndicatorType] ON 

GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  1 ,
                N'Outcome' ,
                N'Outcome' ,
                1,
				N'Outcome'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 1 )
GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  2 ,
                N'Output' ,
                N'Output' ,
                1,
				N'Output'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 2 )
GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  3 ,
                N'SubOutput' ,
                N'SubOutput' ,
                1,
				N'SubOutput'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 3 )
GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  4 ,
                N'Activity' ,
                N'Activity' ,
                1,
				N'Activity'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 4 )
GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  5 ,
                N'Milestone' ,
                N'Milestone' ,
                1,
				N'Milestone'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 5 )
GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  6 ,
                N'OS' ,
                N'Overall Status' ,
                1,
				N'OS'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 6 )
GO



INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  7 ,
                N'PROG' ,
                N'Programme' ,
                1,
				N'PROG'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 7 )
GO

INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  8 ,
                N'SEC' ,
                N'Sector' ,
                1,
				N'SEC'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 8 )
GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  9 ,
                N'SS' ,
                N'SubSector' ,
                1,
				N'SS'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 9 )
GO
INSERT  [app].[IndicatorType]
        ( [app].[IndicatorType].[IndicatorType_ID] ,
          [app].[IndicatorType].[Code] ,
          [app].[IndicatorType].[Name] ,
          [app].[IndicatorType].[Active],
		  [app].[IndicatorType].[BusinessKey]
        )
        SELECT  10,
                N'PRJ' ,
                N'Project' ,
                1,
				N'PRJ'
        WHERE   NOT EXISTS ( SELECT 1
                             FROM   app.IndicatorType
                             WHERE  [app].[IndicatorType].[IndicatorType_ID] = 9 )
GO
SET IDENTITY_INSERT [app].[IndicatorType] OFF
GO


/*Insert settings*/
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

INSERT INTO [settings].[GlobalSettings]
           ([Code]
           ,[Name]
           ,[Value]
           )
     SELECT 
	 Code, Name, Value 
	 FROM (
		SELECT 
		'MMBASEURL' AS Code
		, 'MegaMenu Base URL' AS Name 
		, '/' as Value)
		Src
	 WHERE NOT EXISTS 
	 (SELECT 1 FROM settings.GlobalSettings
	 WHERE Src.Code = GlobalSettings.Code)
	 

	 INSERT INTO [settings].[GlobalSettings]
           ([Code]
           ,[Name]
           ,[Value]
           )
     SELECT 
	 Code, Name, Value 
	 FROM (
		SELECT 
		'BASESITEURL' AS Code
		, 'Fully qualified Base URL' AS Name 
		, 'http://mgs-m6700/sites/Meerkat/' as Value)
		Src
	 WHERE NOT EXISTS 
	 (SELECT 1 FROM settings.GlobalSettings
	 WHERE Src.Code = GlobalSettings.Code)


	 INSERT INTO [settings].[GlobalSettings]
           ([Code]
           ,[Name]
           ,[Value]
           )
     SELECT 
	 Code, Name, Value 
	 FROM (
		SELECT 
		'Client' AS Code
		, 'Client' AS Name 
		, 'CARE Somalia' as Value)
		Src
	 WHERE NOT EXISTS 
	 (SELECT 1 FROM settings.GlobalSettings
	 WHERE Src.Code = GlobalSettings.Code)






/*Insert Forms data*/
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT INTO [forms].[QuestionType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Multiple choice' as Name
	,'MCQ' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[QuestionType]
		WHERE Code = q.Code)

		
INSERT INTO [forms].[QuestionType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Radio Button' as Name
	,'RB' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[QuestionType]
		WHERE Code = q.Code)

INSERT INTO [forms].[QuestionType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Text response' as Name
	,'TR' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[QuestionType]
		WHERE Code = q.Code)

		
INSERT INTO [forms].[QuestionType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )
SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'True or false' as Name
	,'BOOL' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[QuestionType]
		WHERE Code = q.Code)

		

				
INSERT INTO [forms].[QuestionType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )
SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Integer' as Name
	,'INT' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[QuestionType]
		WHERE Code = q.Code)


				
INSERT INTO [forms].[QuestionType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )
SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Decimal' as Name
	,'DEC' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[QuestionType]
		WHERE Code = q.Code)

		
INSERT INTO [forms].[QuestionType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )
SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Count' as Name
	,'CNT' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[QuestionType]
		WHERE Code = q.Code)


INSERT INTO [forms].[RollupType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Sum' as Name
	,'SUM' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[RollupType]
		WHERE Code = q.Code)

GO

INSERT INTO [forms].[RollupType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.TextDescription
FROM
(SELECT 
	 'Average' as Name
	,'AVG' as Code
	,'Arithmetric mean' as TextDescription
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[RollupType]
		WHERE Code = q.Code)
GO

INSERT INTO [forms].[RollupType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Maximum' as Name
	,'MAX' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[RollupType]
		WHERE Code = q.Code)
GO

INSERT INTO [forms].[RollupType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Minimum' as Name
	,'MIN' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[RollupType]
		WHERE Code = q.Code)
GO

INSERT INTO [forms].[RollupType]
           ([Name]
           ,[Code]
           ,[TextDescription]
           )

SELECT Q.Name, Q.Code, Q.Name
FROM
(SELECT 
	 'Count' as Name
	,'CNT' as Code
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [forms].[RollupType]
		WHERE Code = q.Code)

/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET identity_insert disagg.gender on


INSERT INTO [disagg].[Gender]
           ([Gender_ID]
		   ,[Code]
           ,[Name]
		   ,[BusinessKey]
           )
SELECT Q.Gender_ID, Q.Code, Q.Name, Q.BusinessKey
FROM
(SELECT 
	-1 As Gender_ID
	,'UNK' as Code
	,'Unknown' as Name
	,'UNK' as BusinessKey
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [disagg].[Gender]
		WHERE Code = q.Code)

INSERT INTO [disagg].[Gender]
           ([Gender_ID]
		   ,[Code]
           ,[Name]
		   ,[BusinessKey]
           )
SELECT Q.Gender_ID, Q.Code, Q.Name, Q.BusinessKey
FROM
(SELECT 
	0 As Gender_ID
	,'M' as Code
	,'Male' as Name
	,'M' as BusinessKey
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [disagg].[Gender]
		WHERE Code = q.Code)
     


INSERT INTO [disagg].[Gender]
           ([Gender_ID]
		   ,[Code]
           ,[Name]
		   ,[BusinessKey]
           )
SELECT Q.Gender_ID, Q.Code, Q.Name, Q.BusinessKey
FROM
(SELECT 
	1 As Gender_ID
	,'F' as Code
	,'Female' as Name
	,'F' as BusinessKey
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [disagg].[Gender]
		WHERE Code = q.Code)



INSERT INTO [disagg].[Gender]
           ([Gender_ID]
		   ,[Code]
           ,[Name]
		   ,[BusinessKey]
           )
SELECT Q.Gender_ID, Q.Code, Q.Name, Q.BusinessKey
FROM
(SELECT 
	2 As Gender_ID
	,'UND' as Code
	,'Undisclosed' as Name
	,'UND' as BusinessKey
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [disagg].[Gender]
		WHERE Code = q.Code)



SET identity_insert disagg.gender off


/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
set identity_insert disagg.age on
insert into disagg.age (age_id)
select rn -1 from (
select row_number() over(order by name) rn

from sys.all_objects
) src
where rn <= 120
and not exists
(SELECT 1 FROM disagg.Age
where age.Age_ID = rn-1)

set identity_insert disagg.age off

/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

SET identity_insert [rpt].CustomReportType on


INSERT INTO [rpt].[CustomReportType]
           ([CustomReportType_ID]
		   ,[Code]
           ,[Name]
		   ,[BusinessKey]
           )
SELECT Q.CustomReportType_ID, Q.Code, Q.Name, Q.BusinessKey
FROM
(SELECT 
	1 As CustomReportType_ID
	,'DNR' as Code
	,'Donor' as Name
	,'DNR' as BusinessKey
) Q
WHERE NOT EXISTS (
	SELECT 1 FROM [rpt].[CustomReportType]
		WHERE Code = q.Code)

SET identity_insert [rpt].CustomReportType off


/* Insert Demo data */
--:r .\DemoData\PostDeploymentScript.Demo.PDS.sql
									

/*Insert CARE Data */
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
--:r .\CareData\Core.OrganizationType.CARE.PDS.sql
--:r .\CareData\Core.Organization.CARE.PDS.sql
--:r .\app.Outcome.CARE.PDS.sql
--:r .\app.Output.CARE.PDS.sql
--:r .\app.SubOutput.CARE.PDS.sql
--:r .\app.IndicatorMilestone.CARE.PDS.sql
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT INTO [Core].[LocationType]
           ([Code], [Name], [Description], [BusinessKey])
     SELECT
          'CONT' ,'Continent' ,'Continent', 'CONT' WHERE NOT EXISTS (SELECT 1 FROM [Core].[LocationType] WHERE [Code]  ='CONT')

INSERT INTO [Core].[LocationType]
           ([Code], [Name], [Description], [BusinessKey])
     SELECT
          'CNTRY' ,'Country' ,'Country', 'CNTRY' WHERE NOT EXISTS (SELECT 1 FROM [Core].[LocationType] WHERE [Code]  ='CNTRY')

          
INSERT INTO [Core].[LocationType]
           ([Code], [Name], [Description], [BusinessKey])
     SELECT
          'REG' ,'Region' ,'Region', 'REG' WHERE NOT EXISTS (SELECT 1 FROM [Core].[LocationType] WHERE [Code]  ='REG')

          
INSERT INTO [Core].[LocationType]
           ([Code], [Name], [Description], [BusinessKey])
     SELECT
          'DIST' ,'District' ,'District', 'DIST' WHERE NOT EXISTS (SELECT 1 FROM [Core].[LocationType] WHERE [Code]  ='DIST')

INSERT INTO [Core].[LocationType]
           ([Code], [Name], [Description], [BusinessKey])
     SELECT
          'VILG' ,'Village' ,'Village', 'VILG' WHERE NOT EXISTS (SELECT 1 FROM [Core].[LocationType] WHERE [Code]  ='VILG')

GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET IDENTITY_INSERT [Core].[Location] ON
GO

INSERT [Core].[Location] (
    [Location_ID]
    , [Code]
    , [Name]
    , [AreaKM]
    , [Population]
    , [LocationType_ID]
    , [ParentLocation_ID]
    , [Geog]
	, [BusinessKey]
    ) 
    SELECT 1
    , 'SOM' Code
    , 'Somaliland' [Name]
    , 137600
    , 3500000
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'CNTRY')
    , NULL
    , NULL [Geog]
	, 'SOM'
    WHERE NOT EXISTS (
    SELECT 1 FROM [Core].[Location] WHERE Code = 'SOM'
    )

	INSERT [Core].[Location] (
    [Location_ID]
    , [Code]
    , [Name]
    , [AreaKM]
    , [Population]
    , [LocationType_ID]
    , [ParentLocation_ID]
    , [Geog]
	, [BusinessKey]
    ) 
    SELECT 2
    , 'MOG' Code
    , 'Mogadishu' [Name]
    , 1637
    , 1530000
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'CNTRY')
    , NULL
    , NULL [Geog]
	, 'MOG'
    WHERE NOT EXISTS (
    SELECT 1 FROM [Core].[Location] WHERE Code = 'MOG'
    )

	INSERT [Core].[Location] (
    [Location_ID]
    , [Code]
    , [Name]
    , [AreaKM]
    , [Population]
    , [LocationType_ID]
    , [ParentLocation_ID]
    , [Geog]
	, [BusinessKey]
    ) 

    SELECT 3
    , 'PUNT' Code
    , 'Puntland' [Name]
    , 212510
    , 3900000
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'CNTRY')
    , NULL
    , NULL [Geog]
	, 'PUNT'
    WHERE NOT EXISTS (
    SELECT 1 FROM [Core].[Location] WHERE Code = 'PUNT'
    )

SET IDENTITY_INSERT [Core].[Location] OFF
GO

INSERT [Core].[Location] (
    [Code]
    , [Name]
    , [AreaKM]
    , [Population]
    , [LocationType_ID]
    , [ParentLocation_ID]
    , [Geog]
	, [BusinessKey]
    ) 
    SELECT '1' Code
    , 'Lascanood' [Name]
    , NULL 
    , NULL
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'SOM')
    , NULL [Geog]
	, '1'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '1' 
    )	
    

UNION ALL
SELECT '2' Code
    , 'Ainabo' [Name]
    , NULL 
    , NULL
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'SOM')
    , NULL [Geog]
	, '2'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '2' 
    )	
    

UNION ALL
SELECT '3' Code
    , 'Odweyne' [Name]
    , 12245 
    , 1109735
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'SOM')
    , NULL [Geog]
	, '3'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '3' 
    )	
    

UNION ALL
SELECT '4' Code
    , 'Burao' [Name]
    , 35375 
    , 240075
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'SOM')
    , NULL [Geog]
	, '4'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '4' 
    )	
    

UNION ALL
SELECT '5' Code
    , 'Badhan' [Name]
    , 6497 
    , 101539
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'SOM')
    , NULL [Geog]
	, '5'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '5' 
    )	
    

UNION ALL
SELECT '6' Code
    , 'Erigavo' [Name]
    , 17083 
    , 284657
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'SOM')
    , NULL [Geog]
	, '6'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '6' 
    )	
    

UNION ALL
SELECT '7' Code
    , 'El-afweyn' [Name]
    , 45720 
    , 623060
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'SOM')
    , NULL [Geog]
	, '7'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '7' 
    )	
    

UNION ALL
SELECT '8' Code
    , 'Waaberi' [Name]
    , 55840 
    , 661941
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'MOG')
    , NULL [Geog]
	, '8'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '8' 
    )	
    

UNION ALL
SELECT '9' Code
    , 'Wadajir' [Name]
    , 25797 
    , 1025756
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'MOG')
    , NULL [Geog]
	, '9'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '9' 
    )	
    

UNION ALL
SELECT '10' Code
    , 'Hodan' [Name]
    , 66923 
    , 291166
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'MOG')
    , NULL [Geog]
	, '10'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '10' 
    )	
    

UNION ALL
SELECT '11' Code
    , 'Garowe' [Name]
    , 25336 
    , 143294
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '11'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '11' 
    )	
    

UNION ALL
SELECT '12' Code
    , 'Jalam' [Name]
    , 5127 
    , 1356301
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '12'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '12' 
    )	
    

UNION ALL
SELECT '13' Code
    , 'Godobjiran' [Name]
    , 2409 
    , 365330
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '13'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '13' 
    )	
    

UNION ALL
SELECT '14' Code
    , 'Galkacyo' [Name]
    , 2555 
    , 516212
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '14'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '14' 
    )	
    

UNION ALL
SELECT '15' Code
    , 'Gardo' [Name]
    , 24385 
    , 1012709
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '15'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '15' 
    )	
    

UNION ALL
SELECT '16' Code
    , 'Bosasso' [Name]
    , 5952 
    , 1098584
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '16'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '16' 
    )	
    

UNION ALL
SELECT '18' Code
    , 'Taleh' [Name]
    , 3107 
    , 596268
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '18'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '18' 
    )	
    

UNION ALL
SELECT '19' Code
    , 'Kalabyer' [Name]
    , 2361 
    , 693558
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '19'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '19' 
    )	
    

UNION ALL
SELECT '20' Code
    , 'Baran' [Name]
    , 1205 
    , 528054
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '20'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '20' 
    )	
    

UNION ALL
SELECT '21' Code
    , 'Buraan' [Name]
    , 2325 
    , 942581
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'PUNT')
    , NULL [Geog]
	, '21'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '21' 
    )	
    

UNION ALL
SELECT '22' Code
    , 'Hinglool' [Name]
    , 2449 
    , 1623282
    ,(SELECT LocationType_ID FROM [Core].[LocationType] WHERE [Code] = 'DIST')
    , (SELECT Location_ID FROM [Core].[Location] WHERE [Code] = 'KE')
    , NULL [Geog]
	, '22'
    WHERE NOT EXISTS (
        SELECT 1 FROM [Core].[Location] WHERE [Code] = '22' 
    )	   

    /*Location Insert end*/
    /*Update Geography*/

/*IF (CHARINDEX(CONVERT(VARCHAR, SERVERPROPERTY('edition')), N'Express') > -1)
BEGIN    
IF NOT EXISTs (select 1 FROM sys.Databases where Name = 'KenyaShapes')
    
    RAISERROR ('You must restore the KenyaShapes DB to get the geography shapes, obtain it at https://www.dropbox.com/s/jtb9ohpuov51wkt/KenyaShapes.bak', -- Message text.
               18, -- Severity.
               1 -- State.
               );

UPDATE [Core].[Location]
SET Geog = (SELECT Geography::UnionAggregate(geom)
  FROM [KenyaShapes].[dbo].[Counties])
  WHERE [Code] = 'KE'

UPDATE [Core].[Location]
SET Geog = geom
FROM [KenyaShapes].[dbo].[Counties]
  WHERE  [Code] = CAST(COUNTY_COD as varchar(10))
END*/
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

INSERT INTO [app].[Programme]
           ([Code]
           ,[LongName]
           ,[BusinessKey]
           ,[ShortName]
		   ,[ProgrammeSiteName]
           ,[TextDescription]


)
SELECT		src.[Code]
           ,src.[LongName]
           ,src.[Code]
           ,src.[ShortName]
           ,src.[ProgrammeSiteName] 
           ,src.[TextDescription]

FROM (
	SELECT 'RVW' AS Code
		,'Emergency Response Programme' As LongName
		,'Emergency Response' as ShortName
		,'program1' as ProgrammeSiteName
		,'The Emergency Response Program (ERP) provides direct humanitarian relief to communities affected by drought and conflict across Somalia.' As TextDescription
	) Src
	WHERE NOT EXISTS (SELECT 1 FROM app.Programme P WHERE P.BusinessKey = Src.Code)

UNION ALL

SELECT		src.[Code]
           ,src.[LongName]
           ,src.[Code]
           ,src.[ShortName]
           ,src.[ProgrammeSiteName] 
           ,src.[TextDescription]

FROM (
	SELECT 'UYP' AS Code
		,'Urban Youth Programme' As LongName
		,'Urban Youth' as ShortName
		,'program2' as ProgrammeSiteName
		,'The Urban Youth Program (UYP) focuses on job creation and livelihood opportunities for poor youth through e.g. secondary education, vocational training, small business development, and microfinance.' As TextDescription
	) Src
	WHERE NOT EXISTS (SELECT 1 FROM app.Programme P WHERE P.BusinessKey = Src.Code)

UNION ALL
SELECT		src.[Code]
           ,src.[LongName]
           ,src.[Code]
           ,src.[ShortName]
           ,src.[ProgrammeSiteName] 
           ,src.[TextDescription]

FROM (
	SELECT 'RVW' AS Code
		,'Rural Vulnerable Women Programme' As LongName
		,'Rural Women' as ShortName
		,'program3' as ProgrammeSiteName
		,'The Rural Vulnerable Women’s Program (RVWP) supports poor rural women and girls in addressing long term underlying causes of poverty and vulnerability, addressing social, economic, cultural and political obstacles to positive change. We help women and girls improve their economic status, access education and support them to play a greater role in local leadership and conflict resolution.' As TextDescription
	) Src
	WHERE NOT EXISTS (SELECT 1 FROM app.Programme P WHERE P.BusinessKey = Src.Code)

UNION ALL


SELECT		src.[Code]
           ,src.[LongName]
           ,src.[Code]
           ,src.[ShortName]
           ,src.[ProgrammeSiteName] 
           ,src.[TextDescription]

FROM (
	SELECT 'CO' AS Code
		,'Country Office' As LongName
		,'Country Office' as ShortName
		,'program4' as ProgrammeSiteName
		,'The Country Office aggregates information from all programme sites.' As TextDescription
	) Src
	WHERE NOT EXISTS (SELECT 1 FROM app.Programme P WHERE P.BusinessKey = Src.Code)
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

INSERT INTO [settings].[GlobalSettings]
           ([Code]
           ,[Name]
           ,[Value]
           )
     SELECT 
	 Code, Name, Value 
	 FROM (
		SELECT 
		'MMBASEURL' AS Code
		, 'MegaMenu Base URL' AS Name 
		, '/' as Value)
		Src
	 WHERE NOT EXISTS 
	 (SELECT 1 FROM settings.GlobalSettings
	 WHERE Src.Code = GlobalSettings.Code)
	 

	 INSERT INTO [settings].[GlobalSettings]
           ([Code]
           ,[Name]
           ,[Value]
           )
     SELECT 
	 Code, Name, Value 
	 FROM (
		SELECT 
		'BASESITEURL' AS Code
		, 'Fully qualified Base URL' AS Name 
		, 'http://carer03.cloudapp.net/' as Value)
		Src
	 WHERE NOT EXISTS 
	 (SELECT 1 FROM settings.GlobalSettings
	 WHERE Src.Code = GlobalSettings.Code)


	 INSERT INTO [settings].[GlobalSettings]
           ([Code]
           ,[Name]
           ,[Value]
           )
     SELECT 
	 Code, Name, Value 
	 FROM (
		SELECT 
		'Client' AS Code
		, 'Client' AS Name 
		, 'CARE Somalia' as Value)
		Src
	 WHERE NOT EXISTS 
	 (SELECT 1 FROM settings.GlobalSettings
	 WHERE Src.Code = GlobalSettings.Code)



						

--:r .\InternalTest\PostDeploymentScript.InternalTest.PDS.sql	


/*end Insert data*/

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [app].[Project] WITH CHECK CHECK CONSTRAINT [FK_Project_ProjectType];

ALTER TABLE [settings].[TablesToExport] WITH CHECK CHECK CONSTRAINT [FK_TablesToExport_ActiveType];


GO
PRINT N'Update complete.';


GO
