CREATE TABLE [app].[Indicator] (
    [IndicatorID]      INT              IDENTITY (1, 1) NOT NULL,
    [LongName]         VARCHAR (500)    NOT NULL,
    [TextDescription]  VARCHAR (MAX)    NULL,
    [Baseline]         DECIMAL (20, 5)  NULL,
    [BaselineString]   VARCHAR (MAX)    NULL,
    [BaselineDate]     DATETIME         NOT NULL,
    [Target]           DECIMAL (20, 5)  NULL,
    [TargetString]     VARCHAR (MAX)    NULL,
    [TargetDate]       DATETIME         NOT NULL,
    [ReleaseDate]      DATE             NULL,
    [ReportingDate]    DATE             NULL,
    [Output_ID]        INT              NULL,
    [OutcomeID]        INT              NULL,
    [BusinessKey]      NVARCHAR (MAX)   NULL,
    [Notes]            NVARCHAR (MAX)   NULL,
    [Code]             NVARCHAR (20)    NOT NULL,
    [IndicatorType_ID] INT              NOT NULL,
    [Activity_ID]      INT              NULL,
    [SubOutput_ID]     INT              NULL,
    [ShortName]        VARCHAR (50)     NOT NULL,
    [BaselineDate_ID]  AS               ((datepart(year,[BaselineDate])*(10000)+datepart(month,[baselineDate])*(100))+datepart(day,[BaselineDate])),
    [TargetDate_ID]    AS               ((datepart(year,[TargetDate])*(10000)+datepart(month,[TargetDate])*(100))+datepart(day,[TargetDate])),
    [updated]          NVARCHAR (50)    NULL,
    [IsKeyIndicator]   BIT              NOT NULL,
    [UnitOfMeasure]    VARCHAR (50)     NOT NULL,
    [Active]           INT              CONSTRAINT [DF__Indicator__sys_A__4F9CCB9E] DEFAULT ((1)) NOT NULL,
    [projectID]        INT              NULL,
    [sys_CreatedBy]    VARCHAR (255)    CONSTRAINT [DF_Indicator_sys_CreatedBy] DEFAULT (user_name()) NOT NULL,
    [sys_CreatedOn]    DATETIME         CONSTRAINT [DF_Indicator_sys_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [sys_ModifiedBy]   VARCHAR (255)    CONSTRAINT [DF_Indicator_sys_ModifiedBy] DEFAULT (user_name()) NOT NULL,
    [sys_ModifiedOn]   DATETIME         CONSTRAINT [DF_Indicator_sys_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_Indicator_] PRIMARY KEY CLUSTERED ([IndicatorID] ASC),
    CONSTRAINT [CK_ENFORCE_SINGLE_PARENT_LINK_Indicator] CHECK (((((case when [Output_ID] IS NOT NULL then (1) else (0) end+case when [OutcomeID] IS NOT NULL then (1) else (0) end)+case when [Activity_ID] IS NOT NULL then (1) else (0) end)+case when [SubOutput_ID] IS NOT NULL then (1) else (0) end)+case when [projectID] IS NOT NULL then (1) else (0) end)=(1)),
    CONSTRAINT [FK_Indicator_ActiveType] FOREIGN KEY ([Active]) REFERENCES [Core].[ActiveType] ([ID]),
    CONSTRAINT [FK_Indicator_Activity] FOREIGN KEY ([Activity_ID]) REFERENCES [app].[Activity] ([ActivityID]),
    CONSTRAINT [FK_Indicator_IndicatorType] FOREIGN KEY ([IndicatorType_ID]) REFERENCES [app].[IndicatorType] ([IndicatorType_ID]),
    CONSTRAINT [FK_Indicator_Outcome] FOREIGN KEY ([OutcomeID]) REFERENCES [app].[Outcome] ([OutcomeID]),
    CONSTRAINT [FK_Indicator_Output] FOREIGN KEY ([Output_ID]) REFERENCES [app].[Output] ([Output_ID]),
    CONSTRAINT [FK_Indicator_SubOutput] FOREIGN KEY ([SubOutput_ID]) REFERENCES [app].[SubOutput] ([SubOutput_ID])
);

