/*
Deployment script for ND_MeerkatStaging

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ND_MeerkatStaging"
:setvar DefaultFilePrefix "ND_MeerkatStaging"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating [Staging]...';


GO
CREATE SCHEMA [Staging]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [Staging].[Activity]...';


GO
CREATE TABLE [Staging].[Activity] (
    [Activity_ID]        INT            NULL,
    [BusinessKey]        NVARCHAR (400) NOT NULL,
    [Code]               VARCHAR (50)   NOT NULL,
    [LocalLongName]      NVARCHAR (500) NULL,
    [LocalShortName]     NVARCHAR (50)  NULL,
    [LongName]           VARCHAR (500)  NOT NULL,
    [ShortName]          VARCHAR (50)   NOT NULL,
    [TextDescription]    VARCHAR (4000) NULL,
    [ProjectBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[AgeBand]...';


GO
CREATE TABLE [Staging].[AgeBand] (
    [AgeBand_ID]         INT            NULL,
    [BusinessKey]        NVARCHAR (400) NOT NULL,
    [Code]               VARCHAR (50)   NULL,
    [LocalName]          NVARCHAR (255) NULL,
    [Name]               VARCHAR (255)  NULL,
    [TextDescription]    VARCHAR (4000) NULL,
    [AgeBandMax_ID]      INT            NOT NULL,
    [AgeBandMin_ID]      INT            NOT NULL,
    [ProjectBusinessKey] NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[CommunityType]...';


GO
CREATE TABLE [Staging].[CommunityType] (
    [CommunityType_ID] INT            NULL,
    [BusinessKey]      NVARCHAR (400) NOT NULL,
    [Code]             VARCHAR (50)   NOT NULL,
    [LocalName]        NVARCHAR (255) NULL,
    [Name]             VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[CustomReport]...';


GO
CREATE TABLE [Staging].[CustomReport] (
    [CustomReport_ID]             INT            NULL,
    [BusinessKey]                 NVARCHAR (400) NOT NULL,
    [Code]                        VARCHAR (50)   NOT NULL,
    [LocalName]                   NVARCHAR (255) NULL,
    [Name]                        VARCHAR (255)  NOT NULL,
    [CustomReportTypeBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[CustomReport_Calendar]...';


GO
CREATE TABLE [Staging].[CustomReport_Calendar] (
    [CustomReport_Calendar_ID] INT            NULL,
    [ReportDeadlineStartDate]  DATE           NOT NULL,
    [ReportDueDate]            DATE           NOT NULL,
    [ReportNoticeStartDate]    DATE           NOT NULL,
    [ReportWarningStartDate]   DATE           NOT NULL,
    [CustomReportBusinessKey]  NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[CustomReport_Indicator]...';


GO
CREATE TABLE [Staging].[CustomReport_Indicator] (
    [CustomReport_Indicator_ID] INT            NULL,
    [CustomReportBusinessKey]   NVARCHAR (400) NOT NULL,
    [IndicatorBusinessKey]      NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[CustomReport_Project]...';


GO
CREATE TABLE [Staging].[CustomReport_Project] (
    [CustomReport_Project_ID] INT            NULL,
    [CustomReportBusinessKey] NVARCHAR (400) NULL,
    [ProjectBusinessKey]      NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[CustomReport_ResponsiblePerson]...';


GO
CREATE TABLE [Staging].[CustomReport_ResponsiblePerson] (
    [CustomReport_ResponsiblePerson_ID] INT            NULL,
    [CustomReportBusinessKey]           NVARCHAR (400) NULL,
    [PersonBusinessKey]                 NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[CustomReportType]...';


GO
CREATE TABLE [Staging].[CustomReportType] (
    [CustomReportType_ID] INT            NULL,
    [BusinessKey]         NVARCHAR (400) NOT NULL,
    [Code]                VARCHAR (50)   NOT NULL,
    [DeadlineDays]        INT            NOT NULL,
    [LocalName]           NVARCHAR (255) NULL,
    [Name]                VARCHAR (255)  NULL,
    [NoticeDays]          INT            NOT NULL,
    [WarningDays]         INT            NOT NULL
);


GO
PRINT N'Creating [Staging].[DataSource]...';


GO
CREATE TABLE [Staging].[DataSource] (
    [DataSource_ID]    INT            NULL,
    [BusinessKey]      NVARCHAR (400) NOT NULL,
    [CollectionMethod] VARCHAR (MAX)  NULL,
    [ContactDetails]   VARCHAR (MAX)  NULL,
    [Custodian]        VARCHAR (MAX)  NULL,
    [Format]           VARCHAR (MAX)  NULL,
    [LocalName]        NVARCHAR (255) NULL,
    [MetadataStatus]   VARCHAR (MAX)  NULL,
    [Name]             VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[DataVersion]...';


GO
CREATE TABLE [Staging].[DataVersion] (
    [DataVersion_ID] INT            NULL,
    [BusinessKey]    NVARCHAR (400) NOT NULL,
    [Code]           VARCHAR (50)   NOT NULL,
    [Description]    VARCHAR (MAX)  NOT NULL,
    [LocalName]      NVARCHAR (255) NULL,
    [Name]           VARCHAR (255)  NULL,
    [Order]          INT            NOT NULL
);


GO
PRINT N'Creating [Staging].[Donor]...';


GO
CREATE TABLE [Staging].[Donor] (
    [Donor_ID]    INT            NULL,
    [BusinessKey] NVARCHAR (400) NOT NULL,
    [Code]        VARCHAR (50)   NOT NULL,
    [LocalName]   NVARCHAR (255) NULL,
    [Name]        VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[DonorReport]...';


GO
CREATE TABLE [Staging].[DonorReport] (
    [DonorReport_ID] INT            NULL,
    [BusinessKey]    NVARCHAR (400) NOT NULL,
    [Code]           VARCHAR (50)   NOT NULL,
    [LocalName]      NVARCHAR (255) NULL,
    [Name]           VARCHAR (255)  NOT NULL
);


GO
PRINT N'Creating [Staging].[DonorReport_Indicator]...';


GO
CREATE TABLE [Staging].[DonorReport_Indicator] (
    [DonorReport_Indicator_ID] INT            NULL,
    [DonorReportBusinessKey]   NVARCHAR (400) NULL,
    [IndicatorBusinessKey]     NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[DonorReport_Project]...';


GO
CREATE TABLE [Staging].[DonorReport_Project] (
    [DonorReport_Project_ID] INT            NULL,
    [DonorReportBusinessKey] NVARCHAR (400) NULL,
    [ProjectBusinessKey]     NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[Facility]...';


GO
CREATE TABLE [Staging].[Facility] (
    [Facility_ID]             INT            NULL,
    [BusinessKey]             NVARCHAR (400) NOT NULL,
    [Code]                    VARCHAR (50)   NOT NULL,
    [LocalName]               NVARCHAR (255) NULL,
    [Name]                    VARCHAR (255)  NOT NULL,
    [FacilityTypeBusinessKey] NVARCHAR (400) NOT NULL,
    [InstitutionBusinessKey]  NVARCHAR (400) NULL,
    [LocationBusinessKey]     NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[FacilityType]...';


GO
CREATE TABLE [Staging].[FacilityType] (
    [FacilityType_ID] INT            NULL,
    [BusinessKey]     NVARCHAR (400) NOT NULL,
    [Code]            VARCHAR (50)   NOT NULL,
    [LocalName]       NVARCHAR (255) NULL,
    [Name]            VARCHAR (255)  NOT NULL
);


GO
PRINT N'Creating [Staging].[Framework]...';


GO
CREATE TABLE [Staging].[Framework] (
    [Framework_ID]            INT            NULL,
    [BusinessKey]             NVARCHAR (400) NOT NULL,
    [Code]                    VARCHAR (50)   NOT NULL,
    [LocalName]               NVARCHAR (255) NULL,
    [Name]                    VARCHAR (255)  NULL,
    [OrganizationBusinessKey] NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[FrameworkDetail]...';


GO
CREATE TABLE [Staging].[FrameworkDetail] (
    [FrameworkDetail_ID]   INT            NULL,
    [BusinessKey]          NVARCHAR (400) NOT NULL,
    [Code]                 VARCHAR (50)   NOT NULL,
    [LocalName]            NVARCHAR (255) NULL,
    [Name]                 VARCHAR (255)  NULL,
    [FrameworkBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[FrameworkDetail_Indicator]...';


GO
CREATE TABLE [Staging].[FrameworkDetail_Indicator] (
    [FrameworkDetail_Indicator_ID] INT            NULL,
    [BusinessKey]                  NVARCHAR (400) NOT NULL,
    [FrameworkDetailBusinessKey]   NVARCHAR (400) NULL,
    [IndicatorBusinessKey]         NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[FrameworkDetail_Project]...';


GO
CREATE TABLE [Staging].[FrameworkDetail_Project] (
    [FrameworkDetail_Project_ID] INT            NULL,
    [FrameworkDetailBusinessKey] NVARCHAR (400) NULL,
    [ProjectBusinessKey]         NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[Gender]...';


GO
CREATE TABLE [Staging].[Gender] (
    [Gender_ID]   INT            NULL,
    [BusinessKey] NVARCHAR (400) NOT NULL,
    [Code]        VARCHAR (50)   NOT NULL,
    [LocalName]   NVARCHAR (255) NULL,
    [Name]        VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Group]...';


GO
CREATE TABLE [Staging].[Group] (
    [Group_ID]    INT            NULL,
    [BusinessKey] NVARCHAR (400) NOT NULL,
    [Code]        VARCHAR (50)   NOT NULL,
    [LocalName]   NVARCHAR (255) NULL,
    [Name]        VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Impact]...';


GO
CREATE TABLE [Staging].[Impact] (
    [Impact_ID]              INT            NULL,
    [BusinessKey]            NVARCHAR (400) NOT NULL,
    [Code]                   VARCHAR (50)   NOT NULL,
    [ImpactSiteName]         NVARCHAR (50)  NULL,
    [LocalLongName]          NVARCHAR (500) NULL,
    [LocalShortName]         NVARCHAR (50)  NULL,
    [LongName]               VARCHAR (500)  NOT NULL,
    [ShortName]              VARCHAR (50)   NOT NULL,
    [TextDescription]        VARCHAR (4000) NULL,
    [DataVersionBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[Indicator]...';


GO
CREATE TABLE [Staging].[Indicator] (
    [IndicatorID]                    INT             NULL,
    [BusinessKey]                    NVARCHAR (400)  NOT NULL,
    [Baseline]                       DECIMAL (20, 5) NULL,
    [BaselineDate]                   DATETIME        NOT NULL,
    [BaselineString]                 VARCHAR (MAX)   NULL,
    [Code]                           VARCHAR (50)    NOT NULL,
    [LocalLongName]                  NVARCHAR (500)  NULL,
    [LocalShortName]                 NVARCHAR (50)   NULL,
    [LongName]                       VARCHAR (500)   NOT NULL,
    [Notes]                          NVARCHAR (MAX)  NULL,
    [ReleaseDate]                    DATE            NULL,
    [ReportingDate]                  DATE            NULL,
    [ShortName]                      VARCHAR (50)    NOT NULL,
    [Target]                         DECIMAL (20, 5) NULL,
    [TargetDate]                     DATETIME        NOT NULL,
    [TargetString]                   VARCHAR (MAX)   NULL,
    [TextDescription]                VARCHAR (4000)  NULL,
    [UnitOfMeasure]                  VARCHAR (50)    NOT NULL,
    [IndicatorSimpleTypeBusinessKey] NVARCHAR (400)  NULL,
    [IndicatorTypeBusinessKey]       NVARCHAR (400)  NOT NULL,
    [OutcomeBusinessKey]             NVARCHAR (400)  NULL,
    [OutputBusinessKey]              NVARCHAR (400)  NULL,
    [ProgrammeBusinessKey]           NVARCHAR (400)  NULL,
    [ProjectBusinessKey]             NVARCHAR (400)  NULL,
    [ResultAreaBusinessKey]          NVARCHAR (400)  NULL,
    [SectorBusinessKey]              NVARCHAR (400)  NULL,
    [SubOutputBusinessKey]           NVARCHAR (400)  NULL,
    [SubSectorBusinessKey]           NVARCHAR (400)  NULL
);


GO
PRINT N'Creating [Staging].[IndicatorLocation]...';


GO
CREATE TABLE [Staging].[IndicatorLocation] (
    [IndicatorLocation_ID] INT            NULL,
    [IndicatorBusinessKey] NVARCHAR (400) NULL,
    [LocationBusinessKey]  NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[IndicatorSimpleType]...';


GO
CREATE TABLE [Staging].[IndicatorSimpleType] (
    [IndicatorSimpleType_ID] INT            NULL,
    [BusinessKey]            NVARCHAR (400) NOT NULL,
    [Code]                   VARCHAR (50)   NOT NULL,
    [LocalName]              NVARCHAR (255) NULL,
    [Name]                   VARCHAR (255)  NOT NULL
);


GO
PRINT N'Creating [Staging].[IndicatorType]...';


GO
CREATE TABLE [Staging].[IndicatorType] (
    [IndicatorType_ID] INT            NULL,
    [BusinessKey]      NVARCHAR (400) NOT NULL,
    [Code]             VARCHAR (50)   NOT NULL,
    [LocalName]        NVARCHAR (255) NULL,
    [Name]             VARCHAR (255)  NOT NULL
);


GO
PRINT N'Creating [Staging].[IndicatorValues]...';


GO
CREATE TABLE [Staging].[IndicatorValues] (
    [IndicatorValues_ID]         INT             NULL,
    [BusinessKey]                NVARCHAR (400)  NOT NULL,
    [ActualDate]                 DATE            NULL,
    [ActualLabel]                VARCHAR (50)    NOT NULL,
    [ActualValue]                DECIMAL (20, 5) NULL,
    [Notes]                      VARCHAR (MAX)   NULL,
    [AgeBandBusinessKey]         NVARCHAR (400)  NULL,
    [CommunityTypeBusinessKey]   NVARCHAR (400)  NULL,
    [DataVersionBusinessKey]     NVARCHAR (400)  NOT NULL,
    [DonorBusinessKey]           NVARCHAR (400)  NULL,
    [FrameworkBusinessKey]       NVARCHAR (400)  NULL,
    [GenderBusinessKey]          NVARCHAR (400)  NULL,
    [GroupBusinessKey]           NVARCHAR (400)  NULL,
    [IndicatorBusinessKey]       NVARCHAR (400)  NOT NULL,
    [InstitutionBusinessKey]     NVARCHAR (400)  NULL,
    [LocationBusinessKey]        NVARCHAR (400)  NOT NULL,
    [OrganizationBusinessKey]    NVARCHAR (400)  NULL,
    [ReportingPeriodBusinessKey] NVARCHAR (400)  NOT NULL,
    [StructureBusinessKey]       NVARCHAR (400)  NULL
);


GO
PRINT N'Creating [Staging].[Institution]...';


GO
CREATE TABLE [Staging].[Institution] (
    [Institution_ID] INT            NULL,
    [BusinessKey]    NVARCHAR (400) NOT NULL,
    [Code]           VARCHAR (50)   NOT NULL,
    [LocalName]      NVARCHAR (255) NULL,
    [Name]           VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Location]...';


GO
CREATE TABLE [Staging].[Location] (
    [Location_ID]             INT             NULL,
    [BusinessKey]             NVARCHAR (400)  NOT NULL,
    [AreaKM]                  DECIMAL (18, 2) NULL,
    [Code]                    VARCHAR (50)    NOT NULL,
    [Density]                 VARCHAR (MAX)   NULL,
    [LocalName]               NVARCHAR (255)  NULL,
    [Name]                    VARCHAR (255)   NULL,
    [Population]              DECIMAL (18, 2) NULL,
    [ParentLocation_ID]       INT             NULL,
    [LocationTypeBusinessKey] NVARCHAR (400)  NULL
);


GO
PRINT N'Creating [Staging].[LocationType]...';


GO
CREATE TABLE [Staging].[LocationType] (
    [LocationType_ID] INT            NULL,
    [BusinessKey]     NVARCHAR (400) NOT NULL,
    [Code]            VARCHAR (50)   NOT NULL,
    [Description]     VARCHAR (MAX)  NOT NULL,
    [LocalName]       NVARCHAR (255) NULL,
    [Name]            VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Milestone]...';


GO
CREATE TABLE [Staging].[Milestone] (
    [MilestoneID]              INT             NULL,
    [BusinessKey]              NVARCHAR (400)  NOT NULL,
    [Baseline]                 DECIMAL (20, 5) NULL,
    [BaselineDate]             DATETIME        NOT NULL,
    [BaselineString]           VARCHAR (MAX)   NULL,
    [Code]                     VARCHAR (50)    NOT NULL,
    [LocalLongName]            NVARCHAR (500)  NULL,
    [LocalShortName]           NVARCHAR (50)   NULL,
    [LongName]                 VARCHAR (500)   NOT NULL,
    [Notes]                    NVARCHAR (MAX)  NULL,
    [ReleaseDate]              DATE            NULL,
    [ReportingDate]            DATE            NULL,
    [ShortName]                VARCHAR (50)    NOT NULL,
    [Target]                   DECIMAL (20, 5) NULL,
    [TargetDate]               DATETIME        NOT NULL,
    [TargetString]             VARCHAR (MAX)   NULL,
    [TextDescription]          VARCHAR (4000)  NULL,
    [UnitOfMeasure]            VARCHAR (50)    NOT NULL,
    [ActivityBusinessKey]      NVARCHAR (400)  NULL,
    [MilestoneTypeBusinessKey] NVARCHAR (400)  NOT NULL,
    [ProjectBusinessKey]       NVARCHAR (400)  NULL
);


GO
PRINT N'Creating [Staging].[MilestoneLocation]...';


GO
CREATE TABLE [Staging].[MilestoneLocation] (
    [MilestoneLocation_ID] INT            NULL,
    [LocationBusinessKey]  NVARCHAR (400) NOT NULL,
    [MilestoneBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[MilestoneType]...';


GO
CREATE TABLE [Staging].[MilestoneType] (
    [MilestoneTypeID] INT            NULL,
    [BusinessKey]     NVARCHAR (400) NOT NULL,
    [Code]            VARCHAR (50)   NOT NULL,
    [LocalName]       NVARCHAR (255) NULL,
    [Name]            VARCHAR (255)  NOT NULL
);


GO
PRINT N'Creating [Staging].[MilestoneValues]...';


GO
CREATE TABLE [Staging].[MilestoneValues] (
    [MilestoneValues_ID]          INT             NULL,
    [BusinessKey]                 NVARCHAR (400)  NOT NULL,
    [ActualDate]                  DATE            NULL,
    [ActualLabel]                 VARCHAR (50)    NOT NULL,
    [ActualValue]                 DECIMAL (20, 5) NULL,
    [GroupVersion]                INT             NOT NULL,
    [Notes]                       VARCHAR (MAX)   NULL,
    [AgeBandBusinessKey]          NVARCHAR (400)  NULL,
    [CommunityTypeBusinessKey]    NVARCHAR (400)  NULL,
    [DataVersionBusinessKey]      NVARCHAR (400)  NOT NULL,
    [DonorBusinessKey]            NVARCHAR (400)  NULL,
    [FrameworkBusinessKey]        NVARCHAR (400)  NULL,
    [GenderBusinessKey]           NVARCHAR (400)  NULL,
    [GroupBusinessKey]            NVARCHAR (400)  NULL,
    [InstitutionBusinessKey]      NVARCHAR (400)  NULL,
    [LocationBusinessKey]         NVARCHAR (400)  NOT NULL,
    [MilestoneBusinessKey]        NVARCHAR (400)  NOT NULL,
    [OrganizationBusinessKey]     NVARCHAR (400)  NULL,
    [ReportingPeriodBusinessKey]  NVARCHAR (400)  NOT NULL,
    [ResultAreaBusinessKey]       NVARCHAR (400)  NULL,
    [StrategicElementBusinessKey] NVARCHAR (400)  NULL
);


GO
PRINT N'Creating [Staging].[Organization]...';


GO
CREATE TABLE [Staging].[Organization] (
    [Organization_ID]             INT            NULL,
    [BusinessKey]                 NVARCHAR (400) NOT NULL,
    [Code]                        VARCHAR (50)   NULL,
    [LocalLongName]               NVARCHAR (500) NULL,
    [LocalShortName]              NVARCHAR (50)  NULL,
    [LongName]                    VARCHAR (500)  NOT NULL,
    [ShortName]                   VARCHAR (50)   NOT NULL,
    [ParentOrganization_ID]       INT            NULL,
    [OrganizationTypeBusinessKey] NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[OrganizationPersonRole]...';


GO
CREATE TABLE [Staging].[OrganizationPersonRole] (
    [OrganizationPersonRole_ID] INT            NULL,
    [EndDate]                   DATETIME2 (7)  NULL,
    [StartDate]                 DATETIME2 (7)  NULL,
    [OrganizationBusinessKey]   NVARCHAR (400) NULL,
    [PersonBusinessKey]         NVARCHAR (400) NULL,
    [RoleBusinessKey]           NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[OrganizationType]...';


GO
CREATE TABLE [Staging].[OrganizationType] (
    [OrganizationType_ID] INT            NULL,
    [BusinessKey]         NVARCHAR (400) NOT NULL,
    [Code]                VARCHAR (50)   NOT NULL,
    [Description]         VARCHAR (MAX)  NULL,
    [LocalName]           NVARCHAR (255) NULL,
    [Name]                VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Outcome]...';


GO
CREATE TABLE [Staging].[Outcome] (
    [Outcome_ID]             INT            NULL,
    [BusinessKey]            NVARCHAR (400) NOT NULL,
    [Code]                   VARCHAR (50)   NOT NULL,
    [LocalLongName]          NVARCHAR (500) NULL,
    [LocalShortName]         NVARCHAR (50)  NULL,
    [LongName]               VARCHAR (500)  NOT NULL,
    [OutcomeSiteName]        NVARCHAR (50)  NULL,
    [ShortName]              VARCHAR (50)   NOT NULL,
    [TextDescription]        VARCHAR (4000) NULL,
    [DataVersionBusinessKey] NVARCHAR (400) NOT NULL,
    [ImpactBusinessKey]      NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[OutcomeOrganization]...';


GO
CREATE TABLE [Staging].[OutcomeOrganization] (
    [OutcomeOrganization_ID]  INT            NULL,
    [OrganizationBusinessKey] NVARCHAR (400) NULL,
    [OutcomeBusinessKey]      NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[OutcomePersonRole]...';


GO
CREATE TABLE [Staging].[OutcomePersonRole] (
    [OutcomePersonRole_ID] INT            NULL,
    [OutcomeBusinessKey]   NVARCHAR (400) NULL,
    [PersonBusinessKey]    NVARCHAR (400) NULL,
    [RoleBusinessKey]      NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[Output]...';


GO
CREATE TABLE [Staging].[Output] (
    [Output_ID]          INT            NULL,
    [BusinessKey]        NVARCHAR (400) NOT NULL,
    [Code]               VARCHAR (50)   NOT NULL,
    [LocalLongName]      NVARCHAR (500) NULL,
    [LocalShortName]     NVARCHAR (50)  NULL,
    [LongName]           VARCHAR (500)  NOT NULL,
    [ShortName]          VARCHAR (50)   NOT NULL,
    [TextDescription]    VARCHAR (4000) NULL,
    [OutcomeBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[OutputOutputLink]...';


GO
CREATE TABLE [Staging].[OutputOutputLink] (
    [OutputOutputLink_ID] INT            NULL,
    [OutputBusinessKey]   NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[OutputPersonRole]...';


GO
CREATE TABLE [Staging].[OutputPersonRole] (
    [OutputPersonRole_ID] INT            NULL,
    [OutputBusinessKey]   NVARCHAR (400) NULL,
    [PersonBusinessKey]   NVARCHAR (400) NULL,
    [RoleBusinessKey]     NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[PeopleReachedValues]...';


GO
CREATE TABLE [Staging].[PeopleReachedValues] (
    [PeopleReachedValuesID]                INT            NULL,
    [Notes]                                NVARCHAR (MAX) NULL,
    [NumberReached]                        INT            NOT NULL,
    [ActivityBusinessKey]                  NVARCHAR (400) NULL,
    [AgeBandBusinessKey]                   NVARCHAR (400) NULL,
    [CommunityTypeBusinessKey]             NVARCHAR (400) NULL,
    [DataVersionBusinessKey]               NVARCHAR (400) NOT NULL,
    [DonorBusinessKey]                     NVARCHAR (400) NULL,
    [FrameworkBusinessKey]                 NVARCHAR (400) NULL,
    [FrameworkDetail_IndicatorBusinessKey] NVARCHAR (400) NULL,
    [GenderBusinessKey]                    NVARCHAR (400) NULL,
    [GroupBusinessKey]                     NVARCHAR (400) NULL,
    [InstitutionBusinessKey]               NVARCHAR (400) NULL,
    [LocationBusinessKey]                  NVARCHAR (400) NOT NULL,
    [OutcomeBusinessKey]                   NVARCHAR (400) NULL,
    [OutputBusinessKey]                    NVARCHAR (400) NULL,
    [ProgrammeBusinessKey]                 NVARCHAR (400) NULL,
    [ProjectBusinessKey]                   NVARCHAR (400) NULL,
    [ReportingPeriodBusinessKey]           NVARCHAR (400) NOT NULL,
    [ResultAreaBusinessKey]                NVARCHAR (400) NULL,
    [SectorBusinessKey]                    NVARCHAR (400) NULL,
    [StatusTypeBusinessKey]                NVARCHAR (400) NULL,
    [StrategicElementBusinessKey]          NVARCHAR (400) NULL,
    [SubOutputBusinessKey]                 NVARCHAR (400) NULL,
    [SubSectorBusinessKey]                 NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[Person]...';


GO
CREATE TABLE [Staging].[Person] (
    [Person_ID]                          INT            NULL,
    [BusinessKey]                        NVARCHAR (400) NOT NULL,
    [Category]                           VARCHAR (MAX)  NULL,
    [ContactDetails]                     VARCHAR (MAX)  NULL,
    [Name]                               VARCHAR (255)  NULL,
    [Title]                              VARCHAR (MAX)  NULL,
    [UserDetails]                        VARCHAR (50)   NULL,
    [PersonParticipationTypeBusinessKey] NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[PersonParticipationType]...';


GO
CREATE TABLE [Staging].[PersonParticipationType] (
    [PersonParticipationType_ID] INT            NULL,
    [BusinessKey]                NVARCHAR (400) NOT NULL,
    [Code]                       VARCHAR (50)   NULL,
    [Name]                       VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Programme]...';


GO
CREATE TABLE [Staging].[Programme] (
    [Programme_ID]      INT            NULL,
    [BusinessKey]       NVARCHAR (400) NOT NULL,
    [Code]              VARCHAR (50)   NULL,
    [LocalLongName]     NVARCHAR (500) NULL,
    [LocalShortName]    NVARCHAR (50)  NULL,
    [LongName]          VARCHAR (500)  NOT NULL,
    [ProgrammeSiteName] VARCHAR (50)   NULL,
    [ShortName]         VARCHAR (50)   NOT NULL,
    [TextDescription]   VARCHAR (4000) NULL
);


GO
PRINT N'Creating [Staging].[Project]...';


GO
CREATE TABLE [Staging].[Project] (
    [ProjectID]                   INT            NULL,
    [BusinessKey]                 NVARCHAR (400) NOT NULL,
    [Code]                        VARCHAR (50)   NOT NULL,
    [LocalLongName]               NVARCHAR (500) NULL,
    [LocalShortName]              NVARCHAR (50)  NULL,
    [LongName]                    VARCHAR (500)  NOT NULL,
    [ProjectSiteName]             VARCHAR (255)  NOT NULL,
    [ProjectStartDate]            DATETIME       NOT NULL,
    [ShortName]                   VARCHAR (50)   NOT NULL,
    [TextDescription]             VARCHAR (4000) NULL,
    [OutcomeBusinessKey]          NVARCHAR (400) NULL,
    [ProgrammeBusinessKey]        NVARCHAR (400) NULL,
    [ProjectTypeBusinessKey]      NVARCHAR (400) NULL,
    [SectorBusinessKey]           NVARCHAR (400) NULL,
    [StrategicElementBusinessKey] NVARCHAR (400) NULL,
    [SubSectorBusinessKey]        NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[Project_ResultArea]...';


GO
CREATE TABLE [Staging].[Project_ResultArea] (
    [Project_ResultArea_ID] INT            NULL,
    [ProjectBusinessKey]    NVARCHAR (400) NULL,
    [ResultAreaBusinessKey] NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[ProjectType]...';


GO
CREATE TABLE [Staging].[ProjectType] (
    [ProjectType_ID] INT            NULL,
    [BusinessKey]    NVARCHAR (400) NOT NULL,
    [Code]           VARCHAR (50)   NOT NULL,
    [LocalName]      NVARCHAR (255) NULL,
    [Name]           VARCHAR (255)  NOT NULL
);


GO
PRINT N'Creating [Staging].[ReportingPeriod]...';


GO
CREATE TABLE [Staging].[ReportingPeriod] (
    [BusinessKey]     NVARCHAR (400) NOT NULL,
    [EndDateID]       INT            NOT NULL,
    [FirstCycleDate]  DATETIME       NOT NULL,
    [ID]              INT            NOT NULL,
    [LastCycleDate]   DATETIME       NOT NULL,
    [LocalYearName]   NVARCHAR (4)   NULL,
    [ReportingPeriod] INT            NOT NULL,
    [StartDateID]     INT            NOT NULL,
    [Summary]         VARCHAR (50)   NOT NULL,
    [YearName]        CHAR (4)       NOT NULL,
    [YearNumber]      INT            NOT NULL
);


GO
PRINT N'Creating [Staging].[ResultArea]...';


GO
CREATE TABLE [Staging].[ResultArea] (
    [ResultArea_ID] INT            NULL,
    [BusinessKey]   NVARCHAR (400) NOT NULL,
    [Code]          VARCHAR (50)   NOT NULL,
    [LocalName]     NVARCHAR (255) NULL,
    [Name]          VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Role]...';


GO
CREATE TABLE [Staging].[Role] (
    [RoleID]      INT            NULL,
    [BusinessKey] NVARCHAR (400) NOT NULL,
    [Code]        VARCHAR (50)   NOT NULL,
    [Description] VARCHAR (MAX)  NULL,
    [LocalName]   NVARCHAR (255) NULL,
    [Name]        VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[Sector]...';


GO
CREATE TABLE [Staging].[Sector] (
    [Sector_ID]            INT            NULL,
    [BusinessKey]          NVARCHAR (400) NOT NULL,
    [Code]                 VARCHAR (50)   NULL,
    [LocalLongName]        NVARCHAR (500) NULL,
    [LocalShortName]       NVARCHAR (50)  NULL,
    [LongName]             VARCHAR (500)  NOT NULL,
    [ShortName]            VARCHAR (50)   NOT NULL,
    [TextDescription]      VARCHAR (4000) NULL,
    [ProgrammeBusinessKey] NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[StatusType]...';


GO
CREATE TABLE [Staging].[StatusType] (
    [BusinessKey] NVARCHAR (400)  NOT NULL,
    [Code]        VARCHAR (50)    NOT NULL,
    [ID]          INT             NOT NULL,
    [LocalName]   NVARCHAR (255)  NULL,
    [Name]        VARCHAR (255)   NOT NULL,
    [Value]       DECIMAL (20, 2) NOT NULL
);


GO
PRINT N'Creating [Staging].[StatusValues]...';


GO
CREATE TABLE [Staging].[StatusValues] (
    [StatusValuesID]             INT            NULL,
    [Notes]                      NVARCHAR (MAX) NULL,
    [ActivityBusinessKey]        NVARCHAR (400) NULL,
    [DataVersionBusinessKey]     NVARCHAR (400) NOT NULL,
    [IndicatorBusinessKey]       NVARCHAR (400) NULL,
    [LocationBusinessKey]        NVARCHAR (400) NOT NULL,
    [MilestoneBusinessKey]       NVARCHAR (400) NULL,
    [OutcomeBusinessKey]         NVARCHAR (400) NULL,
    [OutputBusinessKey]          NVARCHAR (400) NULL,
    [ProgrammeBusinessKey]       NVARCHAR (400) NULL,
    [ProjectBusinessKey]         NVARCHAR (400) NULL,
    [ReportingPeriodBusinessKey] NVARCHAR (400) NOT NULL,
    [SectorBusinessKey]          NVARCHAR (400) NULL,
    [StatusTypeBusinessKey]      NVARCHAR (400) NULL,
    [SubOutputBusinessKey]       NVARCHAR (400) NULL,
    [SubSectorBusinessKey]       NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[StrategicElement]...';


GO
CREATE TABLE [Staging].[StrategicElement] (
    [StrategicElement_ID] INT            NULL,
    [BusinessKey]         NVARCHAR (400) NOT NULL,
    [Code]                VARCHAR (50)   NOT NULL,
    [LocalName]           NVARCHAR (255) NULL,
    [Name]                VARCHAR (255)  NULL
);


GO
PRINT N'Creating [Staging].[SubOutput]...';


GO
CREATE TABLE [Staging].[SubOutput] (
    [SubOutput_ID]      INT            NULL,
    [BusinessKey]       NVARCHAR (400) NOT NULL,
    [Code]              VARCHAR (50)   NOT NULL,
    [LocalLongName]     NVARCHAR (500) NULL,
    [LocalShortName]    NVARCHAR (50)  NULL,
    [LongName]          VARCHAR (500)  NOT NULL,
    [ShortName]         VARCHAR (50)   NOT NULL,
    [TextDescription]   VARCHAR (4000) NULL,
    [OutputBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[SubOutputPersonRole]...';


GO
CREATE TABLE [Staging].[SubOutputPersonRole] (
    [SubOutputPersonRole_ID] INT            NULL,
    [PersonBusinessKey]      NVARCHAR (400) NULL,
    [RoleBusinessKey]        NVARCHAR (400) NULL,
    [SubOutputBusinessKey]   NVARCHAR (400) NULL
);


GO
PRINT N'Creating [Staging].[SubOutputSubOutputLink]...';


GO
CREATE TABLE [Staging].[SubOutputSubOutputLink] (
    [SubOutputSubOutputLink_ID] INT            NULL,
    [SubOutputBusinessKey]      NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[SubSector]...';


GO
CREATE TABLE [Staging].[SubSector] (
    [SubSector_ID]      INT            NULL,
    [BusinessKey]       NVARCHAR (400) NOT NULL,
    [Code]              VARCHAR (50)   NULL,
    [LocalLongName]     NVARCHAR (500) NULL,
    [LocalShortName]    NVARCHAR (50)  NULL,
    [LongName]          VARCHAR (500)  NOT NULL,
    [ShortName]         VARCHAR (50)   NOT NULL,
    [TextDescription]   VARCHAR (4000) NULL,
    [SectorBusinessKey] NVARCHAR (400) NOT NULL
);


GO
PRINT N'Creating [Staging].[TablesToExport]...';


GO
CREATE TABLE [Staging].[TablesToExport] (
    [TablesToExport_ID] INT           NULL,
    [Table_Name]        VARCHAR (255) NOT NULL,
    [Table_Schema]      VARCHAR (255) NOT NULL
);


GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
