CREATE TABLE [Errors].[IndicatorValues] (
    [QueueID]                     INT             NOT NULL,
    [SSISErrorCode]               INT             NOT NULL,
    [SSISErrorColumn]             INT             NOT NULL,
    [PackageName]                 VARCHAR (255)   NOT NULL,
    [ErrorType]                   VARCHAR (255)   NOT NULL,
    [IndicatorValues_ID]          INT             NULL,
    [ActualDate]                  DATE            NULL,
    [ActualLabel]                 VARCHAR (50)    NOT NULL,
    [ActualValue]                 DECIMAL (20, 5) NULL,
    [AgeBandBusinessKey]          NVARCHAR (400)  NULL,
    [BusinessKey]                 NVARCHAR (400)  NOT NULL,
    [CommunityTypeBusinessKey]    NVARCHAR (400)  NULL,
    [DataVersionBusinessKey]      NVARCHAR (400)  NOT NULL,
    [DonorBusinessKey]            NVARCHAR (400)  NULL,
    [FrameworkBusinessKey]        NVARCHAR (400)  NULL,
    [GenderBusinessKey]           NVARCHAR (400)  NULL,
    [GroupBusinessKey]            NVARCHAR (400)  NULL,
    [IndicatorBusinessKey]        NVARCHAR (400)  NOT NULL,
    [InstitutionBusinessKey]      NVARCHAR (400)  NULL,
    [LocationBusinessKey]         NVARCHAR (400)  NOT NULL,
    [Notes]                       VARCHAR (MAX)   NULL,
    [OrganizationBusinessKey]     NVARCHAR (400)  NULL,
    [ReportingPeriodBusinessKey]  NVARCHAR (400)  NOT NULL,
    [ResultAreaBusinessKey]       NVARCHAR (400)  NULL,
    [StrategicElementBusinessKey] NVARCHAR (400)  NULL,
    [AgeBand_ID]                  INT             NULL,
    [CommunityType_ID]            INT             NULL,
    [DataVersion_ID]              INT             NULL,
    [Donor_ID]                    INT             NULL,
    [Framework_ID]                INT             NULL,
    [Gender_ID]                   INT             NULL,
    [Group_ID]                    INT             NULL,
    [Indicator_ID]                INT             NULL,
    [Institution_ID]              INT             NULL,
    [Location_ID]                 INT             NULL,
    [Organization_ID]             INT             NULL,
    [ReportPeriodID]              INT             NULL,
    [ResultArea_ID]               INT             NULL,
    [StrategicElement_ID]         INT             NULL
);

