CREATE TABLE [Errors].[PeopleReachedValues] (
    [QueueID]                              INT            NOT NULL,
    [SSISErrorCode]                        INT            NOT NULL,
    [SSISErrorColumn]                      INT            NOT NULL,
    [PackageName]                          VARCHAR (255)  NOT NULL,
    [ErrorType]                            VARCHAR (255)  NOT NULL,
    [PeopleReachedValuesID]                INT            NULL,
    [ActivityBusinessKey]                  NVARCHAR (400) NULL,
    [AgeBandBusinessKey]                   NVARCHAR (400) NULL,
    [CommunityTypeBusinessKey]             NVARCHAR (400) NULL,
    [DataVersionBusinessKey]               NVARCHAR (400) NOT NULL,
    [DonorBusinessKey]                     NVARCHAR (400) NULL,
    [FrameworkBusinessKey]                 NVARCHAR (400) NULL,
    [FrameworkDetail_IndicatorBusinessKey] NVARCHAR (400) NULL,
    [GenderBusinessKey]                    NVARCHAR (400) NULL,
    [GroupBusinessKey]                     NVARCHAR (400) NULL,
    [InstitutionBusinessKey]               NVARCHAR (400) NULL,
    [LocationBusinessKey]                  NVARCHAR (400) NOT NULL,
    [Notes]                                NVARCHAR (MAX) NULL,
    [NumberReached]                        INT            NOT NULL,
    [OutcomeBusinessKey]                   NVARCHAR (400) NULL,
    [OutputBusinessKey]                    NVARCHAR (400) NULL,
    [ProgrammeBusinessKey]                 NVARCHAR (400) NULL,
    [ProjectBusinessKey]                   NVARCHAR (400) NULL,
    [ReportingPeriodBusinessKey]           NVARCHAR (400) NOT NULL,
    [ResultAreaBusinessKey]                NVARCHAR (400) NULL,
    [SectorBusinessKey]                    NVARCHAR (400) NULL,
    [StatusTypeBusinessKey]                NVARCHAR (400) NULL,
    [StrategicElementBusinessKey]          NVARCHAR (400) NULL,
    [SubOutputBusinessKey]                 NVARCHAR (400) NULL,
    [SubSectorBusinessKey]                 NVARCHAR (400) NULL,
    [Activity_ID]                          INT            NULL,
    [AgeBand_ID]                           INT            NULL,
    [CommunityType_ID]                     INT            NULL,
    [DataVersion_ID]                       INT            NULL,
    [Donor_ID]                             INT            NULL,
    [Framework_ID]                         INT            NULL,
    [FrameworkDetail_Indicator_ID]         INT            NULL,
    [Gender_ID]                            INT            NULL,
    [Group_ID]                             INT            NULL,
    [Institution_ID]                       INT            NULL,
    [Location_ID]                          INT            NULL,
    [Outcome_ID]                           INT            NULL,
    [Output_ID]                            INT            NULL,
    [Programme_ID]                         INT            NULL,
    [ProjectID]                            INT            NULL,
    [ReportingPeriod_ID]                   INT            NULL,
    [ResultArea_ID]                        INT            NULL,
    [Sector_ID]                            INT            NULL,
    [StatusType_ID]                        INT            NULL,
    [StrategicElement_ID]                  INT            NULL,
    [SubOutput_ID]                         INT            NULL,
    [SubSector_ID]                         INT            NULL
);

