CREATE TABLE [Errors].[Question] (
    [QueueID]                  INT              NOT NULL,
    [SSISErrorCode]            INT              NOT NULL,
    [SSISErrorColumn]          INT              NOT NULL,
    [PackageName]              VARCHAR (255)    NOT NULL,
    [ErrorType]                VARCHAR (255)    NOT NULL,
    [Question_ID]              INT              NULL,
    [Age_ID]                   INT              NULL,
    [AgeBandBusinessKey]       NVARCHAR (400)   NULL,
    [Category_ID]              INT              NOT NULL,
    [Code]                     VARCHAR (50)     NOT NULL,
    [CommunityTypeBusinessKey] NVARCHAR (400)   NULL,
    [DecimalResponse]          DECIMAL (20, 12) NULL,
    [FormResponse_FNVID]       BIGINT           NULL,
    [GenderBusinessKey]        NVARCHAR (400)   NULL,
    [GroupBusinessKey]         NVARCHAR (400)   NULL,
    [InstitutionBusinessKey]   NVARCHAR (400)   NULL,
    [IntegerResponse]          INT              NULL,
    [LocalName]                NVARCHAR (255)   NULL,
    [LocationBusinessKey]      NVARCHAR (400)   NULL,
    [MultipleChoiceResponseID] INT              NULL,
    [Name]                     VARCHAR (255)    NOT NULL,
    [QuestionOrder]            INT              NOT NULL,
    [QuestionType_ID]          INT              NOT NULL,
    [Response]                 VARCHAR (MAX)    NULL,
    [TextDescription]          VARCHAR (4000)   NULL,
    [AgeBand_ID]               INT              NULL,
    [CommunityType_ID]         INT              NULL,
    [Gender_ID]                INT              NULL,
    [Group_ID]                 INT              NULL,
    [Institution_ID]           INT              NULL,
    [Location_ID]              INT              NULL
);

