//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundationAutoCompleteFilter.AutoCompleteFilter {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class JSAutoCompleteFilterX {
        
        protected global::System.Web.UI.WebControls.TextBox Filter;
        
        public static implicit operator global::System.Web.UI.TemplateControl(JSAutoCompleteFilterX target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlFilter() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.Filter = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Filter";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::FoundationAutoCompleteFilter.AutoCompleteFilter.JSAutoCompleteFilterX @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
<!DOCTYPE
html>

<html>

<head>
  
<title></title>
    <script src=""../_layouts/15/FoundationAutoCompleteFilter/js/jquery-1.9.1.js""></script>
    <script src=""../_layouts/15/FoundationAutoCompleteFilter/js/jquery-ui-1.10.3.custom.js""></script>
    <link href=""../_layouts/15/FoundationAutoCompleteFilter/css/jquery-ui-1.10.3.custom.css"" rel=""stylesheet"" />
    <script type=""text/javascript"" >
     
        $(function () {
            alert('inside');
            var FilterValues = [
     ""ActionScript"",
     ""AppleScript"",
     ""Asp"",
     ""BASIC"",
     ""C"",
     ""C++"",
     ""Clojure"",
     ""COBOL"",
     ""ColdFusion"",
     ""Erlang"",
     ""Fortran"",
     ""Groovy"",
     ""Haskell"",
     ""Java"",
     ""JavaScript"",
     ""Lisp"",
     ""Perl"",
     ""PHP"",
     ""Python"",
     ""Ruby"",
     ""Scala"",
     ""Scheme""
            ];
        $( ""#Filter"" ).autocomplete({
            source: FilterValues
            });
        });

    </script>
    </head>
    <body>
        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControlFilter();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n    </body>\r\n    </html>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
