CREATE TABLE [RBM].[PeopleReachedValues] (
    [PeopleReachedValuesID] INT            IDENTITY (1, 1) NOT NULL,
    [Outcome_ID]            INT            NULL,
    [Output_ID]             INT            NULL,
    [SubOutput_ID]          INT            NULL,
    [Programme_ID]          INT            NULL,
    [ProjectID]             INT            NULL,
    [Activity_ID]           INT            NULL,
    [StatusType_ID]         INT            NULL,
    [ReportingPeriod_ID]    INT            NOT NULL,
    [Location_ID]           INT            NOT NULL,
    [DataVersion_ID]        INT            NOT NULL,
    [Notes]                 NVARCHAR (MAX) NULL,
    [Active]                INT            CONSTRAINT [DF_PeopleReachedValues_Active] DEFAULT ((1)) NOT NULL,
    [sys_CreatedBy]         VARCHAR (255)  CONSTRAINT [DF_PeopleReachedValues_sys_CreatedBy] DEFAULT (user_name()) NOT NULL,
    [sys_CreatedOn]         DATETIME       CONSTRAINT [DF_PeopleReachedValues_sys_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [sys_ModifiedBy]        VARCHAR (255)  CONSTRAINT [DF_PeopleReachedValues_sys_ModifiedBy] DEFAULT (user_name()) NOT NULL,
    [sys_ModifiedOn]        DATETIME       CONSTRAINT [DF_PeopleReachedValues_sys_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PeopleReachedValues] PRIMARY KEY CLUSTERED ([PeopleReachedValuesID] ASC),
    CONSTRAINT [CK_PeopleReachedValues] CHECK ((((((case when [PeopleReachedValues].[ProjectID] IS NOT NULL then (1) else (0) end+case when [PeopleReachedValues].[Output_ID] IS NOT NULL then (1) else (0) end)+case when [PeopleReachedValues].[Outcome_ID] IS NOT NULL then (1) else (0) end)+case when [PeopleReachedValues].[Activity_ID] IS NOT NULL then (1) else (0) end)+case when [PeopleReachedValues].[SubOutput_ID] IS NOT NULL then (1) else (0) end)+case when [PeopleReachedValues].[Programme_ID] IS NOT NULL then (1) else (0) end)=(1)),
    CONSTRAINT [FK_PeopleReachedValues_ActiveType] FOREIGN KEY ([Active]) REFERENCES [Core].[ActiveType] ([ID]),
    CONSTRAINT [FK_PeopleReachedValues_Activity] FOREIGN KEY ([Activity_ID]) REFERENCES [app].[Activity] ([Activity_ID]),
    CONSTRAINT [FK_PeopleReachedValues_DataVersion] FOREIGN KEY ([DataVersion_ID]) REFERENCES [Core].[DataVersion] ([DataVersion_ID]),
    CONSTRAINT [FK_PeopleReachedValues_Location] FOREIGN KEY ([Location_ID]) REFERENCES [Core].[Location] ([Location_ID]),
    CONSTRAINT [FK_PeopleReachedValues_Outcome] FOREIGN KEY ([Outcome_ID]) REFERENCES [app].[Outcome] ([Outcome_ID]),
    CONSTRAINT [FK_PeopleReachedValues_Output] FOREIGN KEY ([Output_ID]) REFERENCES [app].[Output] ([Output_ID]),
    CONSTRAINT [FK_PeopleReachedValues_Programme] FOREIGN KEY ([Programme_ID]) REFERENCES [app].[Programme] ([Programme_ID]),
    CONSTRAINT [FK_PeopleReachedValues_Project] FOREIGN KEY ([ProjectID]) REFERENCES [app].[Project] ([ProjectID]),
    CONSTRAINT [FK_PeopleReachedValues_ReportingPeriod] FOREIGN KEY ([ReportingPeriod_ID]) REFERENCES [Core].[ReportingPeriod] ([ID]),
    CONSTRAINT [FK_PeopleReachedValues_StatusType] FOREIGN KEY ([StatusType_ID]) REFERENCES [Core].[StatusType] ([ID]),
    CONSTRAINT [FK_PeopleReachedValues_SubOutput] FOREIGN KEY ([SubOutput_ID]) REFERENCES [app].[SubOutput] ([SubOutput_ID])
);

